### ISSUE TITLE
demo 跑不起来啊 老兄

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#1]
`
C:\Users\Administrator\Desktop\FlutterTencentImPlugin-master\android\src\main\java\top\huic\tencent_im_plugin\listener\TencentImListener.java:69: ����: �Ҳ�������
        resultParams.put("params", params == null ? null : JsonUtil.toJSONString(params));
                                                           ^
  ����:   ��� JsonUtil
  λ��: �� TencentImListener
C:\Users\Administrator\Desktop\FlutterTencentImPlugin-master\android\src\main\java\top\huic\tencent_im_plugin\listener\TencentImListener.java:70: ����: �Ҳ�������
        channel.invokeMethod(LISTENER_FUNC_NAME, JsonUtil.toJSONString(resultParams));
                                                 ^
  ����:   ��� JsonUtil
  λ��: �� TencentImListener
C:\Users\Administrator\Desktop\FlutterTencentImPlugin-master\android\src\main\java\top\huic\tencent_im_plugin\ValueCallBack.java:31: ����: �Ҳ�������
            result.success(JsonUtil.toJSONString(t));
                           ^
  ����:   ��� JsonUtil
  λ��: �� ValueCallBack<T>
  ����, T�����ͱ��:
    T�չ������ ValueCallBack��������Object
ע: C:\Users\Administrator\Desktop\FlutterTencentImPlugin-master\android\src\main\java\top\huic\tencent_im_plugin\TencentImPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\Administrator\Desktop\FlutterTencentImPlugin-master\android\src\main\java\top\huic\tencent_im_plugin\TencentImPlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
3 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tencent_im_plugin:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by JiangJuHong** [comment]
抱歉，这可能是我发布最新版本时疏忽的一个错误

**Comment by yuefeng007** [comment]
我还要感谢你嘞，最近会修复吗？

**Comment by JiangJuHong** [comment]
它已经被修复，现在重新拉取项目即可正常运行 @yuefeng007

**Comment by yuefeng007** [comment]
感谢，我去试试

**Comment by yuefeng007** [comment]
爱了，明天接入项目

**Comment by JiangJuHong** [comment]
哈哈，感谢支持

**Comment by JiangJuHong** [comment]
这个插件现在还处于测试阶段，并且会不断改进，如果你打算接入到正式项目中，希望你多给予反馈并随时关注最新版本，测试阶段版本号为： `v0.1.x`，当它大于这个版本时则代表已通过测试并处于稳定版本。

**Comment by yuefeng007** [comment]
ok，要接正式项目，有问题我会随时提 issue。也请老哥多多帮助。另外，近期有计划支持 位置消息和小视频消息吗。我们项目消息类型的需求有，文本。语音、图片、小视频，以及位置。 5种消息类型
