### ISSUE TITLE
添加插件后 iOS端运行报错

### ISSUE THREAD

**Issue by Lanhaoo** [JiangJuHong/FlutterTencentImPlugin#100]
报错原因： 
- `HandyJSON` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
<img width="1197" alt="屏幕快照 2020-10-12 15 39 52" src="https://user-images.githubusercontent.com/38837048/95718607-444b8500-0ca1-11eb-8ab1-306949335ee8.png">

**Comment by JiangJuHong** [comment]
pod install 或 pod update 或参考demo

**Comment by Lanhaoo** [comment]
不好意思哈 我刚刚用了pod install 和pod update 都还是报错
[!] Unable to determine Swift version for the following pods:

- `HandyJSON` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

你说的参考demo是什么意思，没法参考呀。。。。

**Comment by JiangJuHong** [comment]
运行demo，或尝试先谷歌百度

**Comment by Lanhaoo** [comment]
demo在安卓上面可以运行，iOS上面也是运行报错

**Comment by Lanhaoo** [comment]
已解决:
https://www.freesion.com/article/3401520/

**Comment by yunliang** [comment]
我还是有这个问题,能说说详细一点吗?万分感谢.
