### ISSUE TITLE
直播聊天室发送消息的问题

### ISSUE THREAD

**Issue by Lanhaoo** [JiangJuHong/FlutterTencentImPlugin#103]
a，b两个用户在同一个聊天室(AVChatRoom)，用户a发了一条消息，b用户收不到。去腾讯后台看到
<img width="1010" alt="屏幕快照 2020-10-15 17 21 16" src="https://user-images.githubusercontent.com/38837048/96104466-77914c80-0f0b-11eb-84c9-ced5eed7665f.png">
这种应该是发消息发失败了吧。
<img width="672" alt="屏幕快照 2020-10-15 17 22 10" src="https://user-images.githubusercontent.com/38837048/96104053-f20d9c80-0f0a-11eb-9cba-7d460e1c24d7.png">
这个方法没有进入error分支，也没得错误码，不知道该怎么排查问题了

**Comment by JiangJuHong** [comment]
你好，发送失败会返回 error 信息，不存在正常流程跳过，请仔细排查

**Comment by Lanhaoo** [comment]
> 你好，发送失败会返回 error 信息，不存在正常流程跳过，请仔细排查

问题找到了。消息发成功了，是接收的时候出的问题。你的demo中聊天的界面没有实现消息刷新
<img width="798" alt="屏幕快照 2020-10-15 18 37 16" src="https://user-images.githubusercontent.com/38837048/96112634-88df5680-0f15-11eb-93c7-a52b296e273a.png">
我修改了一下
<img width="752" alt="屏幕快照 2020-10-15 18 40 32" src="https://user-images.githubusercontent.com/38837048/96112885-e5427600-0f15-11eb-96f4-edc0870fc2d6.png">

**Comment by JiangJuHong** [comment]
好的，如果方便，建议提交PR，Demo目前并不完善，如果在有时间升级下一个SDK版本后，将会完善Demo
