### ISSUE TITLE
返回 Instance of 'SessionEntity' 的数据，正常的吗？

### ISSUE THREAD

**Issue by chinafelix** [JiangJuHong/FlutterTencentImPlugin#105]
[Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity']

我调用TencentImPlugin.getConversationList()，返回以上的数据，这种数据是正常的吗？如果是，该格式怎么解析成json呢？

**Comment by JiangJuHong** [comment]
这种数据正常，不需要解析为json，此结果是因为使用的print，请尝试使用debug进行调试
