### ISSUE TITLE
提示插件有写API过时

### ISSUE THREAD

**Issue by chinafelix** [JiangJuHong/FlutterTencentImPlugin#106]
你好，安装插件后，启动项目，提示有API过时；

![image](https://user-images.githubusercontent.com/20641047/98104197-15f04c80-1ed1-11eb-9a2c-e59fef5ff343.png)

**Comment by chinafelix** [comment]
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by JiangJuHong** [comment]
这个提示不影响使用，可忽略。造成提示原因有可能为 Flutter for Android 代码 或 IM SDK Android 代码 使用了过时的API。
