### ISSUE TITLE
会话列表数据有时候会报错，有时候正常

### ISSUE THREAD

**Issue by chinafelix** [JiangJuHong/FlutterTencentImPlugin#108]
使用TencentImPlugin.getConversationList()渲染会话列表，有时候会报错：The getter 'sessionType' was called on null.
当我用了断点调试，就不会报错

**Comment by JiangJuHong** [comment]
为了排查方便，请列出的你版本号、设备信息、错误日志信息

**Comment by JiangJuHong** [comment]
FlutterTencentIM插件已更新至 1.0.x，基于v5 SDK，优化参数、枚举等内容，如需要更新，请参考文档进行更新。注意：由于腾讯云 5.x api改动较大，请不要混用 5.x 和 4.x 接口，对应插件版本: 5.x -> 1.x ，4.x -> 0.x。项目地址：https://github.com/JiangJuHong/FlutterTencentImPlugin

**Comment by chinafelix** [comment]
版本：tencent_im_plugin: ^0.2.44；
设备：用的android studio的模拟器；
![image](https://user-images.githubusercontent.com/20641047/98677390-e9887480-2397-11eb-90f5-a3d81b2b4385.png)

如果我在渲染之前设置了断点，一步一步往下走，再渲染就不会出现这个错；

**Comment by JiangJuHong** [comment]
请问你是新集成的还是已经存在项目中很久了？
如果是新集成，建议直接使用最新版本。
------------------
此错误为你传递的 sessionType 值为null，请检查 Chat.dart 205 行 56 列
