### ISSUE TITLE
TencentImPlugin.removeListener没有用，执行后监听依然还在

### ISSUE THREAD

**Issue by debugksir** [JiangJuHong/FlutterTencentImPlugin#110]

**Comment by JiangJuHong** [comment]
等提供你的代码，并确定 addListener 和 removeListener 为相同对象

**Comment by debugksir** [comment]
@JiangJuHong 
https://github.com/JiangJuHong/FlutterTencentImPlugin/blob/master/example/lib/page/chat.dart
用的就是案例中的代码
在dispose中removeListener了监听函数， 但是重新进入会话页面的时候， 对方发送1条消息，监听会收到2条
每进入一次会话页面，监听就会多一条，意味着removeListener没有生效

**Comment by JiangJuHong** [comment]
参考 #45

**Comment by debugksir** [comment]
好吧！
我在flutter/.pub-cache/hosted/pub.flutter-io.cn/tencent_im_plugin-1.0.6/lib/listener/tencent_im_plugin_listener.dart
新加了一个方法，解决了问题
```
  /// 移除所有消息监听
  void removeAllListener() {
    listeners = Set();
  }
```
还是在这里感谢大佬的帮助和开源库🙏

**Comment by JiangJuHong** [comment]
这是一种解决办法，但我认为问题造成的原因可能是由于使用不当
