### ISSUE TITLE
在ios上无法运行，貌似是architecture的问题？

### ISSUE THREAD

**Issue by debugksir** [JiangJuHong/FlutterTencentImPlugin#111]
Target debug_universal_framework failed: Exception: Unsupported iOS arch name ""
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Using build description from disk
    warning: AssetsLibrary is deprecated. Consider migrating to Photos instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'FLAnimatedImage' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'camera' from project 'Pods')
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'camera' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Runner' from project 'Runner')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (armv64, i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Runner' from project
    'Runner')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Pods-Runner' from project 'Pods')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Pods-Runner' from project
    'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'TXIMSDK_iOS' from project 'Pods')

**Comment by debugksir** [comment]
在mac的模拟器上运行报错， 但是执行flutter build ios正常， 所以猜测可能原因是由于真实手机的架构是 arm64，而mac模拟器的架构是 x86-64导致的， 请问大佬有什么解决方案吗

**Comment by JiangJuHong** [comment]
你好，我在xcode中使用模拟器能正常运行

**Comment by debugksir** [comment]
在pubspec.yaml去掉tencent_im_plugin插件，并没有出现这个问题，按照google上提的一些方案， 修改VALID_ARCHS = "arm64 arm64e armv7 armv7s x86_64"，或者$(ARCHS_STANDARD)都没有效，就很奇怪

```
    Target debug_universal_framework failed: Exception: Unsupported iOS arch name ""
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Using build description from disk
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'camera' from project 'Pods')
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'camera' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Runner' from project 'Runner')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Runner' from project
    'Runner')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Pods-Runner' from project 'Pods')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Pods-Runner' from project
    'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'FLAnimatedImage' from project 'Pods')
    warning: AssetsLibrary is deprecated. Consider migrating to Photos instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'DKPhotoGallery' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'TXIMSDK_iOS' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).
sirk@sirdeMacBook-Pro doctor_admin % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by debugksir** [comment]
![image](https://user-images.githubusercontent.com/22571830/99755726-706ee700-2b26-11eb-8b95-f4c3d0e372fb.png)

s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' } 不懂ios开发， 这个语句表示什么呢？

**Comment by JiangJuHong** [comment]
见注释：Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
`Flutter 仅支持 x86_64 位的模拟器`，请确认您的模拟器版本。

此问题将会被关闭。
