### ISSUE TITLE
flutter run 报错

### ISSUE THREAD

**Issue by gitdogogo** [JiangJuHong/FlutterTencentImPlugin#115]
![image](https://user-images.githubusercontent.com/47263325/102171811-567cb600-3ed2-11eb-90c4-2ea15fe31af5.png)

**Comment by gitdogogo** [comment]
下载代码之后进入template目录，pub get 完成后 flutter run  就报这个错

**Comment by JiangJuHong** [comment]
请确保flutter版本是最新，且运行 pub get

**Comment by gitdogogo** [comment]
更新flutter版本之后好了
