### ISSUE TITLE
TencentImPlugin.login怎么确定登录成功了呢

### ISSUE THREAD

**Issue by gitdogogo** [JiangJuHong/FlutterTencentImPlugin#117]
我点到login登录方法中去，看到的时如下的静态方法，不是一个Future的方法
static login({
    @required String userID,
    @required String userSig,
  }) {
    return _channel
        .invokeMethod('login', {"userID": userID, "userSig": userSig});
  }

**Comment by JiangJuHong** [comment]
此类方法代表Future<void>，只要   执行到 .then ，则代表登录成功，也可以  await Tenxxx.login()，执行成功后代表登录成功

**Comment by gitdogogo** [comment]
如果我使用await TencentImPlugin.login则会报错

**Comment by JiangJuHong** [comment]
请贴出详细错误信息或参考Demo

**Comment by gitdogogo** [comment]
我在控制台看到一些链接超时，不太确定是不是登录的，但是await之后的代码没有执行到，如果是登录超时，那么应该怎么处理呢
[asyn_socket_base.cpp, operator, 506]:AsynBaseSocket socket connect timeout|fd:113|type:TCP|
I/Unknow  (18853): [tx_dr_tcp_channel.cpp, OnConnect, 431]:CTXDataReportNetThread OnConnect socketId:113, bSuccess:0, mSocketStatus:2
D/Unknow  (18853): [TXCIOLooper.cpp, CancelPeriodTask, 482]:IOLooper: cancel period task|id:3
I/Unknow  (18853): [asyn_socket_base.cpp, Connect, 466]:AsynBaseSocket socket connect do|fd:113|type:TCP|nRet:0|ip:14.119.113.112|port:20166|

**Comment by JiangJuHong** [comment]
请使用   .then().catchError  写法，其中如果执行  catchError 分支，则代表执行错误

**Comment by gitdogogo** [comment]
我打印了报错信息，提示SDK未初始化，我尝试添加之后好了

谢谢
