### ISSUE TITLE
无网络的时候，如何查询本地历史消息？

### ISSUE THREAD

**Issue by JackZhang1994** [JiangJuHong/FlutterTencentImPlugin#121]
插件版本：0.2.44
手机在无网络的时候，调用TencentImPlugin.getLocalMessages()方法返回9508
那么如何查询本地历史消息？是当前插件版本的腾讯 sdk不支持吗？新版本支持该功能吗？

在新版本的腾讯SDK中，看到了下面这个方法
![image](https://user-images.githubusercontent.com/20792223/102480078-c2117f80-409a-11eb-9194-173a3c38e37e.png)
我的理解是，若App没网时，加载本地数据库中消息；如果有网，优先从远端(漫游)拉取数据。
那么，会不会出现从远端拉取数据耗时较长的情况？目前是否有优化方案？

**Comment by JiangJuHong** [comment]
请先调用  `initStorage` 接口

**Comment by JackZhang1994** [comment]
我试一下，谢谢

**Comment by JackZhang1994** [comment]
您好，试了一下您sdk-v-4.6分支里的demo，登录后进入聊天页面，能看到消息列表。断网后再次进入，也会报9508。
但是master分支的demo，就可以在无网状态拉取到历史消息。

请问是老版本sdk的问题吗？您老版本的插件还继续维护吗？

**Comment by JiangJuHong** [comment]
建议升级为v5，v4暂时停止维护。

**Comment by JackZhang1994** [comment]
好的，知道了，谢谢
