### ISSUE TITLE
为什么每次启动apk之后获取到的user都是null呢

### ISSUE THREAD

**Issue by gitdogogo** [JiangJuHong/FlutterTencentImPlugin#123]
![image](https://user-images.githubusercontent.com/47263325/102753898-107a9300-43a7-11eb-96eb-05cffd57c857.png)
我设置的过期时间是7天啊

**Comment by gitdogogo** [comment]
需要我这边先持久化user，然后用user查询登录状态吗？

**Comment by JiangJuHong** [comment]
额...建议签名在服务端生成，前端生成存在安全隐患

**Comment by JiangJuHong** [comment]
有效期是签名的有效期...代表这个签名只能使用7天，不是登录后7天

**Comment by gitdogogo** [comment]
好的，谢谢
