### ISSUE TITLE
添加好友报错

### ISSUE THREAD

**Issue by mjshwy1991** [JiangJuHong/FlutterTencentImPlugin#124]
调用插件的添加好友接口
addFriend 添加报错。
返回报错码。
Err_SNS_FriendAdd_Source_Illegal,30001

**Comment by JiangJuHong** [comment]
参考腾讯云错误码： 30001，根据字面意思描述，为好友来源错误，请确保参数 "来源" 的正确性

**Comment by JiangJuHong** [comment]
addSource
