### ISSUE TITLE
当我使用android studio打开android目录时，flutter的包找不到

### ISSUE THREAD

**Issue by gitdogogo** [JiangJuHong/FlutterTencentImPlugin#125]
![image](https://user-images.githubusercontent.com/47263325/102980508-a4cd2d00-4542-11eb-9689-3ade3b894dd3.png)
如图中看到的，flutter的包是灰色、红色，怎样才能不报错呢，我在flutter的issues下看到很多这样的问题，有一个答案是我打开的目录错误，需要打开example/android目录，但是我打开这个目录之后却没有TencentIm的相关代码，请教一下这里是怎么回事，需要怎么解决呢？

**Comment by JiangJuHong** [comment]
````
有一个答案是我打开的目录错误，需要打开example/android目录，但是我打开这个目录之后却没有TencentIm的相关代码
````
需要打开 example/android 目录，打开目录后目录结构如下：
![image](https://user-images.githubusercontent.com/17740963/102989544-bcabad80-4550-11eb-8c23-06437ab19e84.png)

**Comment by gitdogogo** [comment]
> ```
> 有一个答案是我打开的目录错误，需要打开example/android目录，但是我打开这个目录之后却没有TencentIm的相关代码
> ```
> 
> 需要打开 example/android 目录，打开目录后目录结构如下：
> ![image](https://user-images.githubusercontent.com/17740963/102989544-bcabad80-4550-11eb-8c23-06437ab19e84.png)


我打开的是这样

**Comment by gitdogogo** [comment]
![image](https://user-images.githubusercontent.com/47263325/103048398-75adce80-45c9-11eb-8c98-39e9c5d83e7c.png)
我打开是这样的，没有哪些代码

**Comment by JiangJuHong** [comment]
直接搜索代码片段 “public class TencentImPlugin”点进去，然后定位过去吧

**Comment by gitdogogo** [comment]
删除代码，重新拉取解决
