### ISSUE TITLE
下载进度中无法区分下载的是什么类型的数据

### ISSUE THREAD

**Issue by shingohu** [JiangJuHong/FlutterTencentImPlugin#129]
目前只返回了msgId来做标识,但是video和videoThumbnail 来源同一个msgId,无法区分,建议DownloadProgressEntity 新增一个类型参数 比如是语音 视频 还是视频缩略图

**Comment by JiangJuHong** [comment]
这似乎是一个有用的建议，我会考虑在接下来几个版本中进行增加。感谢您的建议。

**Comment by JiangJuHong** [comment]
v1.2.7 修复了此问题
