### ISSUE TITLE
跑GitHub上代码iOS模拟器报错

### ISSUE THREAD

**Issue by ligui-iOS** [JiangJuHong/FlutterTencentImPlugin#13]
FlutterTencentImPlugin-master/ios/Classes/SwiftTencentImPlugin.swift:1712:67: error: use of unresolved identifier 'GroupTipsMessageEntity'
            self.invokeListener(type: ListenerType.GroupTips, params: GroupTipsMessageEntity(elem: elem));

TXIMSDK_iOS版本：4.7.2

**Comment by JiangJuHong** [comment]
你好，这是预期之内的错误，是由于第三方插件引起的，目前插件作者没有回应，你可以通过手动将报错地方进行改正。可使用 xcode 智能提示改正。

**Comment by JiangJuHong** [comment]
抱歉，它是由于我的代码没有提交完全造成的，它将在 `v0.2.20` 被修复

**Comment by JiangJuHong** [comment]
`v0.2.20`现已发布
