### ISSUE TITLE
会话列表单聊未读数累计问题

### ISSUE THREAD

**Issue by mirai027** [JiangJuHong/FlutterTencentImPlugin#131]
api接口：TencentImPlugin.getConversationList

会话列表中单聊未读数有时不更新数据，好友发送消息太快导致会话列表得到的是上一次数据的未读数（群数据并未此发生问题）。

**Comment by JiangJuHong** [comment]
此问题请咨询腾讯云工单。

**Comment by mirai027** [comment]
> 此问题请咨询腾讯云工单。

**Comment by mirai027** [comment]
> 此问题请咨询腾讯云工单。

web端接入腾讯IM没有此问题

**Comment by JiangJuHong** [comment]
此插件仅对SDK进行封装，不会更改数据内容。如果出现数据异常问题，请根据文档上的SDK版本号咨询腾讯云工单。
