### ISSUE TITLE
iOS上报推送token

### ISSUE THREAD

**Issue by chiluo** [JiangJuHong/FlutterTencentImPlugin#132]
Android有setOfflinePushConfig，iOS目前貌似不能上报，是否能加个方法

**Comment by JiangJuHong** [comment]
IOS依旧调用此方法，Token为通过APNS获得的Token

**Comment by chiluo** [comment]
ios上调用setOfflinePushConfig必定闪退，只提示Lost connection to device，请问有什么解决办法吗
