### ISSUE TITLE
添加好友监听不到

### ISSUE THREAD

**Issue by ShenKelly** [JiangJuHong/FlutterTencentImPlugin#133]
addFriend的监听没有走进去，但是不报错，把接口换成收发消息接口就没问题，后台已经改成了需验证，checkFriend也是返回的none，没有头绪

**Comment by JiangJuHong** [comment]
我会排查这个问题，如果存在，它将被修复

**Comment by JiangJuHong** [comment]
检查后发现监听不存在问题，请检查 addFriend 接口的返回值是否正确：以下为错误示例：
![image](https://user-images.githubusercontent.com/17740963/104114570-d450a780-5340-11eb-8dda-a20e3ed4454d.png)

**Comment by ShenKelly** [comment]
> 检查后发现监听不存在问题，请检查 addFriend 接口的返回值是否正确：以下为错误示例：
> ![image](https://user-images.githubusercontent.com/17740963/104114570-d450a780-5340-11eb-8dda-a20e3ed4454d.png)

找到问题了，是addSource错误，我只要不传就可以了，请问addSource应该传什么参数呢

**Comment by JiangJuHong** [comment]
这个不太清楚，我在腾讯云IM还没找到关于这个参数的描述，只是说明是一个String
