### ISSUE TITLE
TencentImPlugin.revokeMessage(message: FindMessageEntity (msgId:item.msgID)) 撤回后历史消息中依然存在

### ISSUE THREAD

**Issue by zyyzhy** [JiangJuHong/FlutterTencentImPlugin#134]
TencentImPlugin.revokeMessage(message: FindMessageEntity (msgId:item.msgID)) 撤回该消息后，监听也显示已撤回，获取历史消息，该条消息依然存在。

**Comment by JiangJuHong** [comment]
你好，消息撤回或删除后消息并不会消失，只是消息状态`status`会对应变更为撤回或删除!
