### ISSUE TITLE
多次初始化导致监听器回调多次

### ISSUE THREAD

**Issue by KingTheWin** [JiangJuHong/FlutterTencentImPlugin#135]
当我初始化sdk和登录后进行TencentImPlugin.logout和TencentImPlugin.unInitSDK进行注销，
然后再初始化sdk且登录后，发现监听消息的回调会出现多个；是否是反初始化有问题？

**Comment by JiangJuHong** [comment]
请确保 addListener 只调用了一次，参考: #45

**Comment by KingTheWin** [comment]
我确保了addListener只是调用了一次，也在销毁页面的时候调用了removeListener，

**Comment by KingTheWin** [comment]
我多次测试发现是有多少次初始化sdk，接收就有会多少个回调重复

**Comment by JiangJuHong** [comment]
请确保initSDK也只调用了一次，如果此接口也只调用了一次，请检查每次监听器触发时 listener的数量

**Comment by JiangJuHong** [comment]
initSDK在整个程序运行期间只允许调用一次

**Comment by KingTheWin** [comment]
因为我initSDK的APPID是动态的，我需要在登录的时候格外获取APPID进行初始化，在最后退出登录的时候我也进行了反初始化，然后会跳转登录页，从而进行下一次的initSDK。

**Comment by JiangJuHong** [comment]
现在不支持移除监听器，它将在下一个迭代被支持

**Comment by KingTheWin** [comment]
好的，了解了，谢谢。

**Comment by JiangJuHong** [comment]
fix: 1.2.13
