### ISSUE TITLE
发送语音后，点击播放，iOS端报错

### ISSUE THREAD

**Issue by maitianyihu** [JiangJuHong/FlutterTencentImPlugin#136]
发送语音后，点击播放，iOS端报错。xcode日志如下：
result	() -> ()	0x000000011b4c703c tencent_im_plugin`reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>) -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> ()partial apply forwarder with unmangled suffix ".439"

**Comment by JiangJuHong** [comment]
请提供错误信息、设备信息、以及复现步骤。

**Comment by maitianyihu** [comment]
聊天会话中发送语音消息后，点击我发送的语音消息进行收听时，xocde 日志输出如下：

2021-01-29 19:40:34.002841+0800 Runner[14994:3560484] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(4, download failed, download failed, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
<asynchronous suspension>
#2      _ImItemAudioWidgetState._onPressSound.<anonymous closure>.<anonymous closure> (package:riki_im/pages/chat/item/im_item_audio_widget.dart:218)
<asynchronous suspension>

设备信息:iphone XR 和 iphone X 均为14.2 系统

**Comment by JiangJuHong** [comment]
请注意关键信息：`download failed, download failed`，请仔细检查下载路径，或在 Flutter层进行逐一排查。如果不行，请将相同代码运行在android设备上进行尝试。

**Comment by maitianyihu** [comment]
是这样的，我们安卓端没有问题，Flutter层追踪到调用插件downloadSound方法前都没有明显问题，路径我们也尝试过指定路径，文件消息如excel正常下载都没有问题。使用相同的逻辑旧版本的getSound方法能够正常下载语音消息。   现在的情况是只有新版SDK语音在iOS端会出现问题。

**Comment by maitianyihu** [comment]
此问题我们联调了昨天一下午加今天一下午，实在没有办法了来请教一下，在群里我有放截图，希望大佬能够指点一下。

**Comment by JiangJuHong** [comment]
请尝试以下解决办法：
1. 在下载之前，确保所属目录存在，但是所属文件不存在
2. 在下载之前，确保所属目录存在，且所属文件存在，且文件为空。
