### ISSUE TITLE
关于消息重发resendMessage方法的问题

### ISSUE THREAD

**Issue by m5314** [JiangJuHong/FlutterTencentImPlugin#138]
我在调用resendMessage重新发送消息的时候，监听器返回消息发送成功时msgID对不上，想问一下这里要怎么关联上？

**Comment by JiangJuHong** [comment]
如果你只想展示新消息，可将发送失败的那一条消息进行删除。

**Comment by m5314** [comment]
> 如果你只想展示新消息，可将发送失败的那一条消息进行删除。

如果同时有多条失败的消息，这时需要直到发送成功的这条对应的是哪条失败的消息

**Comment by JiangJuHong** [comment]
发送成功会有回调事件，可以参考文档中的：“回调事件”部分
