### ISSUE TITLE
求 saveMessage  findMessages 这两个接口

### ISSUE THREAD

**Issue by iyuhang** [JiangJuHong/FlutterTencentImPlugin#14]
亟需saveMessage  findMessages 这两个接口
昨天关于，给会话加自定义参数的需求，想了一下可以通过上面这两个接口实现
初始创建会话时，向会话里 saveMessage，然后每次读取的时候使用 findMessages 查找对应的消息

使用 flutter 本地缓存来实现的方式，需要会话循环遍历，太影响会话列表性能，

API | 描述
-- | --
saveMessage | 向本地消息列表中添加一条消息，但并不将其发送出去。
importMsg | 将消息导入本地数据库。
findMessages | 根据提供的消息定位符查找相应消息。

![image](https://user-images.githubusercontent.com/14176635/78419519-2c070780-7679-11ea-832c-a5fad86bfe0f.png)

**Comment by iyuhang** [comment]
同时 saveMessage 这个接口也需要被用来创建会话，但不向对方发送消息

没有这个接口好像只能通过向对方发送消息来创建一个本地会话列表显示的的会话

**Comment by JiangJuHong** [comment]
它将在 ``v0.2.20`` 被提供

**Comment by JiangJuHong** [comment]
`v0.2.20`现已发布
