### ISSUE TITLE
请问下新版的群简介怎么拿到，之前的版本会话列表中可以取到群简介

### ISSUE THREAD

**Issue by 965390267** [JiangJuHong/FlutterTencentImPlugin#146]

**Comment by JiangJuHong** [comment]
[GroupInfoEntity](https://pub.dev/documentation/tencent_im_plugin/latest/entity_group_info_entity/GroupInfoEntity-class.html)中包含群简介信息，如果会话中不存在群简介，可通过[getGroupsInfo](https://pub.dev/documentation/tencent_im_plugin/latest/tencent_im_plugin/TencentImPlugin/getGroupsInfo.html)接口进行获取。
