### ISSUE TITLE
android createGroup 返回的groupID有非法字符 "

### ISSUE THREAD

**Issue by meson-larry** [JiangJuHong/FlutterTencentImPlugin#148]
android 创建群的时候若不指定groupID，返回的groupID是 `"@TGS#24VZFGJHD"` 而不是 `@TGS#24VZFGJHD`。
若不把 " 去掉，getConversation 会返回错误。

临时方案
`    if (groupID != null && groupID.contains('"')) {`
 `     groupID = groupID.substring(1, groupID.length - 1);`
`    }`

**Comment by JiangJuHong** [comment]
好的，我会尝试解决这个问题，在有结果后我会在此回复

**Comment by JiangJuHong** [comment]
fix 2.0.3
