### ISSUE TITLE
ios setGroupInfo必须指定全部字段，否则其他字段会被清空（android没这个问题）

### ISSUE THREAD

**Issue by meson-larry** [JiangJuHong/FlutterTencentImPlugin#149]
ios临时修复代码如下。不过会导致 GroupTipsMessageNode.groupChangeInfoList 包含多条 GroupChangedInfoEntity。

      final updatedGroupInfo = Platform.isIOS
          ? GroupInfoEntity(
              groupID: groupInfo.groupID,
              groupName: groupName ?? groupInfo.groupName,
              notification: notification ?? groupInfo.notification,
              introduction: introduction ?? groupInfo.introduction,
              faceUrl: faceUrl ?? groupInfo.faceUrl,
              allMuted: allMuted ?? groupInfo.allMuted,
            )
          : GroupInfoEntity(
              groupID: groupInfo.groupID,
              groupName: groupName,
              notification: notification,
              introduction: introduction,
              faceUrl: faceUrl,
              allMuted: allMuted,
            );

**Comment by JiangJuHong** [comment]
我正在尝试复现以及解决这个问题，如果有进度我会在此进行回复

**Comment by JiangJuHong** [comment]
抱歉，我尝试通过demo复现此问题，但是内容并未复现

**Comment by JiangJuHong** [comment]
最新进度：通过未传递name参数造成修改introduction错误

**Comment by JiangJuHong** [comment]
fix 2.0.3
