### ISSUE TITLE
日志没有显示

### ISSUE THREAD

**Issue by iyuhang** [JiangJuHong/FlutterTencentImPlugin#15]
现在调试过程里没有打印日志
是否能加上日志控制

日志事件
IM SDK 内部会进行打印日志，如果调用方有自己统一的日志收集方式，可以通过 TIMSdkConfig 中的 setLogListener 接口设置日志事件回调，把日志通过回调返给调用方，但 IM SDK 内部仍然会打印，如果需要禁掉，可以通过设置控制台不打印日志，或者设置日志级别。

**Comment by JiangJuHong** [comment]
它将在 `v0.2.20` 被提供

**Comment by JiangJuHong** [comment]
`v0.2.20`现已发布
