### ISSUE TITLE
请问直接关闭App的时候有办法让IM执行退出登录操作吗？

### ISSUE THREAD

**Issue by sec7et** [JiangJuHong/FlutterTencentImPlugin#152]
请问直接关闭App的时候有办法让IM执行退出登录操作吗？
iOS下，把App直接上划关闭后，IM仍然会保持在线状态，这个应该怎么处理呢？

**Comment by JiangJuHong** [comment]
断开与腾讯服务器连接后，过段时间会自动退出，如果需要监听状态，需要用到服务端进行回调配置。
如果退出后依旧能收到消息，请检查是否配置了离线推送/TPNS
