### ISSUE TITLE
如何更新本地的IM用户的信息呢？

### ISSUE THREAD

**Issue by sec7et** [JiangJuHong/FlutterTencentImPlugin#153]
我和A聊过天，在聊天会话列表里出现过。
这时候A去更新了头像，后端也去调用了更新IM个人资料的SDK接口。
这时候我去聊天列表页面，A的头像还是老的头像，我是从ConversationEntity中取的faceUrl字段。
这是不是因为有本地持久化的原因？我应该怎么做才能更新本地的用户信息呢？

**Comment by sec7et** [comment]
```TencentImPlugin.getConversationList();```中获取的到了```conversationResultEntity?.conversationList```数组，遍历获得```ConversationEntity```对象

**Comment by JiangJuHong** [comment]
目前此接口直接调用的腾讯云IM SDK接口，暂不清楚内部缓存机制，你可以通过更新后再次调用`TencentImPlugin.getConversationList()`，经测试，更新后调用 `TencentImPlugin.getConversationList()` 效果正常。并未出现未刷新问题。

**Comment by sec7et** [comment]
> 目前此接口直接调用的腾讯云IM SDK接口，暂不清楚内部缓存机制，你可以通过更新后再次调用`TencentImPlugin.getConversationList()`，经测试，更新后调用 `TencentImPlugin.getConversationList()` 效果正常。并未出现未刷新问题。

尴尬，我的会话列表页面每次进来都会重新刷新，也就是会重新调用`TencentImPlugin.getConversationList()`接口。而且我尝试了退出登录后再重新登录，甚至关闭App重新运行。均是老头像。

**Comment by JiangJuHong** [comment]
请确保更新是否真的成功...

**Comment by sec7et** [comment]
> 请确保更新是否真的成功...

确实更新成功了。我把App卸载了重装，重新登录后，进入聊天会话列表页面，拉取的数据就是新的头像了。
