### ISSUE TITLE
可以支持下 insertC2CMessageToLocalStorage 这个方法嘛？

### ISSUE THREAD

**Issue by zuiaijj** [JiangJuHong/FlutterTencentImPlugin#156]
我看dart测的API只有insertGroupMessageToLocalStorage，没有对C2C消息的本地插入。我看原生端是有这个方法的，能支持下这个功能嘛？

**Comment by JiangJuHong** [comment]
近期会支持，到时候可通过git方式引入

**Comment by JiangJuHong** [comment]
最新master分支已增加，可通过git方式引入使用
