### ISSUE TITLE
发送失败后，调用resendMessage接口，并不能改变消息的发送状态status（依旧为MessageStatusEnum.SendFail）

### ISSUE THREAD

**Issue by zuiaijj** [JiangJuHong/FlutterTencentImPlugin#157]
我在发送视频失败后，尝试调用resendMessage重新发送，发现重发的新消息的发送状态依旧是MessageStatusEnum.SendFail，我预期的状态是发送中MessageStatusEnum.SendSucc;

我自己现在的解决方案是，先调用deleteMessages删除掉发送失败的消息，再重新调用sendMessage发送。

**Comment by JiangJuHong** [comment]
resendMessage 原理为内部克隆消息然后重新发送，并不会更改原消息（部分需求需要展示发送失败）。所以如果你有删除需求，可以先调用resendMessage，然后再调用 deleteMessage.
