### ISSUE TITLE
安卓机在进行会话监听时闪退

### ISSUE THREAD

**Issue by senmao1994** [JiangJuHong/FlutterTencentImPlugin#161]
<img width="1413" alt="WX20211122-104820@2x" src="https://user-images.githubusercontent.com/50578587/142793851-c704875d-fb91-42d8-a206-1c3e7c49a9dc.png">
D/AndroidRuntime( 5750): Shutting down VM
E/AndroidRuntime( 5750): FATAL EXCEPTION: main
E/AndroidRuntime( 5750): Process: com.xiaodujiankang.doctor, PID: 5750
E/AndroidRuntime( 5750): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 5750): 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.message.entity.CustomMessageEntity.<init>(CustomMessageEntity.java:34)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.message.CustomMessageNode.analysis(CustomMessageNode.java:26)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.message.CustomMessageNode.analysis(CustomMessageNode.java:12)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.entity.CustomMessageEntity.<init>(CustomMessageEntity.java:150)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.entity.CustomConversationEntity.<init>(CustomConversationEntity.java:91)
E/AndroidRuntime( 5750): 	at top.huic.tencent_im_plugin.listener.CustomConversationListener.onNewConversation(CustomConversationListener.java:52)
E/AndroidRuntime( 5750): 	at com.tencent.imsdk.v2.V2TIMConversationManagerImpl$1.onNewConversation(V2TIMConversationManagerImpl.java:80)
E/AndroidRuntime( 5750): 	at com.tencent.imsdk.conversation.ConversationManager$1$4.run(ConversationManager.java:74)
E/AndroidRuntime( 5750): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 5750): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5750): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 5750): 	at android.app.ActivityThread.main(ActivityThread.java:7876)
E/AndroidRuntime( 5750): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5750): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 5750): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/Process ( 5750): Sending signal. PID: 5750 SIG: 9
Lost connection to device.

**Comment by senmao1994** [comment]
<img width="1413" alt="WX20211122-104820@2x" src="https://user-images.githubusercontent.com/50578587/142793906-9595c732-097a-4eb4-bd6d-64f926918b2f.png">

**Comment by JiangJuHong** [comment]
生产环境还是Debug环境

**Comment by JiangJuHong** [comment]
可以通过AS运行，然后在 ``CustomMessageEntity.java`` 147 行打一个Debug，我看看数据

**Comment by senmao1994** [comment]
debug环境 稍等 我试试

**Comment by JiangJuHong** [comment]
自定义消息没有传递Data字段吗？

**Comment by senmao1994** [comment]
会话监听我是在首页做的。这时候都没有调用自定义消息传递 
<img width="1413" alt="WX20211122-104820@2x" src="https://user-images.githubusercontent.com/50578587/142794443-bef5b3c4-c50a-40c9-be09-ee400285e8d4.png">

**Comment by JiangJuHong** [comment]
此字段为必传的，如果不传递此字段，不仅android会出错，ios也会出错。故android没有进行非空判断:
````java
this.data = new String(elem.getData());
````

**Comment by JiangJuHong** [comment]
和会话监听没关系，你自定义消息没数据，内部收到会话后会获取最后一条消息，进而进行解析自定义消息。

**Comment by JiangJuHong** [comment]
堆栈信息是由于你收到了新会话事件，然后解析最后一条消息时出错，请确保 CustomMessage 中的 data 属性不为空。

**Comment by senmao1994** [comment]
可是我的监听中 还没有做相关处理 而且 我还没有做自定义消息发送 = =
![image](https://user-images.githubusercontent.com/50578587/142794759-6955560a-4a80-4785-958f-c57902b3f88b.png)
这是需要在监听中我本身就需要对自定义消息先做判断吗

**Comment by JiangJuHong** [comment]
不需要，是你消息中本来就存在一条自定义消息(之前发送的或通过其他平台发送的)

**Comment by senmao1994** [comment]
那我现在是需要在会话监听里面判断 还是在发送时就要判断

**Comment by JiangJuHong** [comment]
发送时，自定义消息的data属性不能为空，如果要删除本次会话，请删关闭监听器，然后手动调用删除会话接口，然后可以再打开监听器。

**Comment by JiangJuHong** [comment]
需要查看具体的消息内容，请使用 AS启动，在 CustomMessageNode 中的26行打一个debug

**Comment by senmao1994** [comment]
刚询问了我的同事 因为 自定义消息是后台发送的 data字段 他没有用到 也就说可能真的会为空 --

**Comment by JiangJuHong** [comment]
更新最新Ref，内容作了兼容判断，不过自定义消息的data依旧不建议传递空数据，如果此内容为空，那就代表此消息无效。

**Comment by senmao1994** [comment]
好的 谢谢。因为我们这边 服务端同事用的字段是ext 没用data字段

**Comment by senmao1994** [comment]
已经可以了 谢谢大佬～

**Comment by senmao1994** [comment]
Unhandled Exception: LateInitializationError: Field 'data' has not been initialized.
使用自定义消息的时候 报错
因为data 传入的是空字符串

**Comment by senmao1994** [comment]
![image](https://user-images.githubusercontent.com/50578587/143271683-fc172bdf-ad38-4efe-ba22-d207c2b3024f.png)
使用的最新的分支

**Comment by JiangJuHong** [comment]
好的，明天修复

**Comment by senmao1994** [comment]
好的 谢谢大佬

**Comment by senmao1994** [comment]
想问下我这边 自定义消息发送时 是成功的 但是监听收到时 data和ext 这两个字段都是null 数据是已经存进去了 但是就是监听返回时没有值

**Comment by JiangJuHong** [comment]
拉取最新ref即可

> Unhandled Exception: LateInitializationError: Field 'data' has not been initialized. 使用自定义消息的时候 报错 因为data 传入的是空字符串 安卓端

拉取最新即可
