### ISSUE TITLE
通过ref引入编译失败

### ISSUE THREAD

**Issue by zuiaijj** [JiangJuHong/FlutterTencentImPlugin#164]
![image](https://user-images.githubusercontent.com/39050602/158594680-355fffce-9b3c-48e9-aa9a-2813bec100fb.png)
我在尝试通过git引入插件时，出现了这个编译错误，我不太熟悉IOS开发，不知道这可能是什么问题导致的？

**Comment by JiangJuHong** [comment]
请尝试使用ref：ceaafafd4ef7a4569892b63e423925bbf861b481，最新的ref有点问题，会在近期修复

**Comment by zuiaijj** [comment]
好的，多谢，我试试看
