### ISSUE TITLE
似乎是一个bug

### ISSUE THREAD

**Issue by Mzrong** [JiangJuHong/FlutterTencentImPlugin#20]
1、消息监听器，会重复回调。比如：type为ListenerTypeEnum.RefreshConversation收到一条消息，会回调两次。type为ListenerTypeEnum.NewMessages时则是根据点了多少次Run按钮来的（Android Studio上那个绿色三角形）。比如点了5次，收到新消息就有5次回调。
2、TencentImPlugin.initStorage()。第一次无法初始化
希望大佬能够看一下，谢谢了

**Comment by JiangJuHong** [comment]
你是运行的 example 还是 自有项目？ `TencentImPlugin.initStorage()。第一次无法初始化` 能否提供更加详细的说明，如果报错，能否提供错误日志

**Comment by Mzrong** [comment]
报的这个错：PlatformException(9519, Execution Error, packet in queue but no available channel to send)。
我这边运行的是自己的项目。我是启动App的时候，在main.dart中做的初始化，第一次运行的时候是会报这个错。后面就不会了

**Comment by JiangJuHong** [comment]
你好，这是腾讯云内部错误码，你可以根据错误提示进行错误诊断，如果确定是IM插件内部错误，那么我会将它修改。但是目前为止，我还没有遇到过这个错误。
![image](https://user-images.githubusercontent.com/17740963/79551152-de07f000-80cb-11ea-8c65-f6490082ecc1.png)

**Comment by JiangJuHong** [comment]
```
ERR_SDK_NET_WAIT_SEND_TIMEOUT               = 9519,    ///< 请求包已进入待发送队列，等待进入系统的网络 buffer 超时，数据包较多 或 发送线程处理不过来，内部错误。
```

**Comment by Mzrong** [comment]
谢谢老哥，您再看看新消息监听，多次回调的这个问题。我不确定是否是代码的bug，或者还是插件的bug

**Comment by JiangJuHong** [comment]
这个我在插件里面也没有复现，你有没有尝试在 example 中复现？我猜测可能是由于你多次注册了监听，但是没有进行销毁造成的

**Comment by Mzrong** [comment]
好的，我仔细检查下代码试试看看。谢谢老哥，感谢老哥的无私开源

**Comment by programmerElephant** [comment]
> 好的，我仔细检查下代码试试看看。谢谢老哥，感谢老哥的无私开源

只要登录一次，回调就会增加一次，在测试的时候，重新运行时候需要注销账号，这样就不会收到多次

**Comment by YDJSZY** [comment]
@programmerElephant 我重新登录前也有注销账号了，但还是会收到多次回调
