### ISSUE TITLE
[优化] 调用原生代码时，确保MethodResult被调用

### ISSUE THREAD

**Issue by yohom** [JiangJuHong/FlutterTencentImPlugin#22]
防止dart端没有接收原生返回导致一直挂起。
比如logout方法：
https://github.com/JiangJuHong/FlutterTencentImPlugin/blob/fd5f8ef5695862ea60b0a01638a719e9bbe2842c/android/src/main/java/top/huic/tencent_im_plugin/TencentImPlugin.java#L386
如果没有用户登录的话，MethodResult不会被调用，导致dart端一直接收不到结果。其他方法应该也有类似的情况。
另外问一下，用户的登录之后，是不是只有调用了登出方法，状态才会是登出状态？还是说app被杀死，或者断网之类的情况都会使用户处在登出状态？

**Comment by JiangJuHong** [comment]
抱歉，我可能忽略了部分方法，我会检查并发布新版本

**Comment by JiangJuHong** [comment]
它在 `0.2.25` 被修复
