### ISSUE TITLE
设置加好友选项

### ISSUE THREAD

**Issue by yohom** [JiangJuHong/FlutterTencentImPlugin#23]
目前调用addFriend方法后，对方直接就变成了自己的好友，没有发现配置加好友选项的地方。
看官方文档应该是有这样一个方法来配置：
```java
TIMFriendshipManager.getInstance().setAllowType(TIMFriendAllowType.TIM_FRIEND_NEED_CONFIRM, new TIMCallBack(){
 @Override
 public void onError(int code, String desc){
 //错误码code和错误描述desc，可用于定位请求失败原因
 //错误码code列表请参见错误码表
 Log.e(tag, "setAllowType failed: " + code + " desc");
 }
```
还是说是我没找到接口？

**Comment by JiangJuHong** [comment]
我明天为你检查一下，我记得之前我有添加一个

**Comment by yohom** [comment]
现在有配置的入口吗，我看到有`getPendencyList`系列的接口，如果没有可以配置成`需要验证`的模式，那`getPendencyList`系列的接口不是都排不上用场了吗😂

**Comment by JiangJuHong** [comment]
你可以先仔细找找，因为我在生产项目上已经使用了，并且加好友和 &nbsp;未决申请，审核 &nbsp; 是正常的

**Comment by yohom** [comment]
找到了，`modifySelfProfile`，感谢老铁。
另外问一下，我调用`await TencentImPlugin.initStorage`的时候，dart代码会直接挂起不返回，我storage权限也已经请求了，可能会是什么问题？

**Comment by JiangJuHong** [comment]
可能是发生了错误？使用 then catch 方式试试呢

**Comment by yohom** [comment]
老铁可以加个微信吗 18072488657，给你发个红包😄顺便后续还有一些问题需要请教下你

**Comment by JiangJuHong** [comment]
发红包就可以不用啦，维护这个项目是我应该的，微信我加你吧，我的昵称是阿弥陀佛
