### ISSUE TITLE
调用获得群未决列表方法报异常getGroupPendencyList

### ISSUE THREAD

**Issue by ligui-iOS** [JiangJuHong/FlutterTencentImPlugin#26]
E/flutter ( 6252): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.Long cannot be cast to java.lang.Integer, null)

**Comment by JiangJuHong** [comment]
它将在下个版本被修复

**Comment by ligui-iOS** [comment]
包括处理加群消息方法groupPendencyRefuse也报了类型转换错误，大佬大概什么时候发布下个版本

**Comment by JiangJuHong** [comment]
它以及类似的错误在 `0.2.30` 被修复
