### ISSUE TITLE
在群聊中，有點小問題

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#29]
1：若訊息量大，不能去到底部（最新訊息）
2. 新訊息沒有更新，
LISTENER收到NEW MESSAGE，但是在   
 this.setState(() {
        data.add(params)
      });
這裡死了

**Comment by JiangJuHong** [comment]
您好，第一个问题请参考Google进行代码编写。第二个问题可能是您的Flutter代码出现错误，请仔细检查您的代码。

**Comment by wilson0506** [comment]
2: 我沒改過，只運行EXAMPLE：
line 182: https://github.com/JiangJuHong/FlutterTencentImPlugin/blob/master/example/lib/page/im.dart

**Comment by JiangJuHong** [comment]
能否提供一下 add 相关的错误信息，有助于排查

**Comment by wilson0506** [comment]
落一個TRY CATCH 去看？
我是運行這句前後放個PRINT，看到行到這里便卡住了

**Comment by JiangJuHong** [comment]
这个问题在 `0.2.32` 被修复
