### ISSUE TITLE
打包 apk后 得到的会话实体<SessionEntity>，好像是有问题，我不太能确定是否是我的问题！

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#3]
1. ### 我得到的会话实体<SessionEntity>中  的id，和type  是null
2. 
3. `I/flutter ( 2892): null  <SessionEntity.id>
4. I/flutter ( 2892): null  <SessionEntity.type>`
5. 
6. `IM初始化成功
7. I/flutter ( 2892): onRefresh
8. I/flutter ( 2892): res:0
9. I/flutter ( 2892): home页面listener被触发
10. I/flutter ( 2892): null
11. I/flutter ( 2892): ListenerTypeEnum.Connected
12. I/flutter ( 2892): im登录成功
13. I/flutter ( 2892): home页面listener被触发
14. I/flutter ( 2892): null
15. I/flutter ( 2892): ListenerTypeEnum.Refresh
16. I/flutter ( 2892): home页面listener被触发
17. I/flutter ( 2892): [Instance of 'SessionEntity']
18. I/flutter ( 2892): ListenerTypeEnum.RefreshConversation
19. I/flutter ( 2892): Instance of 'SessionEntity'
20. I/flutter ( 2892): null  <SessionEntity.id>
21. I/flutter ( 2892): null  <SessionEntity.type>
22. E/flutter ( 2892): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Missing parameter, Cannot find parameter `sessionId` or `sessionId` is null!, 5)
23. E/flutter ( 2892): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
24. E/flutter ( 2892): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
25. E/flutter ( 2892): <asynchronous suspension>
26. E/flutter ( 2892): #2      TencentImPlugin.getLocalMessages (package:tencent_im_plugin/tencent_im_plugin.dart:186)
27. E/flutter ( 2892): #3      _ChatDetailState._init.<anonymous closure> (package:chatpear/modules/home/chat_detail.dart:71)
28. E/flutter ( 2892): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102)
29. E/flutter ( 2892): #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049)
30. E/flutter ( 2892): #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957)
31. E/flutter ( 2892): #7      _rootRun (dart:async/zone.dart:1126)
32. E/flutter ( 2892): #8      _CustomZone.run (dart:async/zone.dart:1023)
33. E/flutter ( 2892): #9      _CustomZone.runGuarded (dart:async/zone.dart:925)
34. E/flutter ( 2892): #10     _invoke (dart:ui/hooks.dart:259)
35. E/flutter ( 2892): #11     _drawFrame (dart:ui/hooks.dart:217)
36. E/flutter ( 2892): 
37. E/flutter ( 2892): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Missing parameter, Cannot find parameter `sessionId` or `sessionId` is null!, 5)
38. E/flutter ( 2892): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
39. E/flutter ( 2892): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
40. E/flutter ( 2892): <asynchronous suspension>
41. E/flutter ( 2892): #2      TencentImPlugin.getMessages (package:tencent_im_plugin/tencent_im_plugin.dart:204)
42. E/flutter ( 2892): #3      _ChatDetailState.onRefresh (package:chatpear/modules/home/chat_detail.dart:149)
43. E/flutter ( 2892): #4      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:357)
44. E/flutter ( 2892): #5      _rootRunUnary (dart:async/zone.dart:1134)
45. E/flutter ( 2892): #6      _CustomZone.runUnary (dart:async/zone.dart:1031)
46. E/flutter ( 2892): #7      _FutureListener.handleValue (dart:async/future_impl.dart:139)
47. E/flutter ( 2892): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
48. E/flutter ( 2892): #9      Future._propagateToListeners (dart:async/future_impl.dart:709)
49. E/flutter ( 2892): #10     Future._completeWithValue (dart:async/future_impl.dart:524)
50. E/flutter ( 2892): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554)
51. E/flutter ( 2892): #12     _rootRun (dart:async/zone.dart:1126)
52. E/flutter ( 2892): #13     _CustomZone.run (dart:async/zone.dart:1023)
53. E/flutter ( 2892): #14     _CustomZone.runGuarded (dart:async/zone.dart:925)
54. E/flutter ( 2892): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
55. E/flutter ( 2892): #16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
56. E/flutter ( 2892): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
57. E/flutter ( 2892): `

**Comment by JiangJuHong** [comment]
我未测试过打包，你得到的所有会话都有问题吗？或者只是其中某个

**Comment by yuefeng007** [comment]
获取会话列表时，我的会话列表中只有一天对话。感觉这条会话实体是拿到了。我尝试输出它的id和type的。但是输出结果是null

**Comment by yuefeng007** [comment]
可以在log日志中第20条和第21条看到

**Comment by JiangJuHong** [comment]
建议你多创建几个会话，Group、C2C，这样有便于排查错误

**Comment by yuefeng007** [comment]
好的，我明天多创建一些会话试试

**Comment by yuefeng007** [comment]
本次测试账号中 存在 4条会话，一个Group和三个C2C， 在debug模式下正常运行，

打包apk后，虽然接到一个 会话实体《SessionEntity》，但实体中多有的数据 都是null
debug版本 图一
build apk  版本  图二
![微信图片_20200302111838](https://user-images.githubusercontent.com/38639357/75642836-e620e300-5c77-11ea-8915-56e1fed3c620.jpg)
![65a3e2e92a1f93687a5252f56aa65e9](https://user-images.githubusercontent.com/38639357/75642907-23857080-5c78-11ea-85a4-348b8a7b8324.png)

**Comment by yuefeng007** [comment]
好像不对，我在试试 再回复

**Comment by yuefeng007** [comment]
终于测明白了
本次测试账号共四条会话  ，一个Group、三个C2C。
使用方法：
```
 TencentImPlugin.addListener((type,params){
   if (type == ListenerTypeEnum.RefreshConversation) {
         devbug和build 版本 均正确返回数组
        [ Instance of 'SessionEntity'  *  4]
   }
});
但是  build版本中的 [ Instance of 'SessionEntity'  *  4]  中 每个的属性都是nul
```
debug：log:
```
home页面listener被触发  --start---
I/flutter (15282): [Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity']
I/flutter (12706): 已添加会话id:15545111710,会话类型type：SessionType.C2C
I/flutter (12706): 已添加会话id:15545111711,会话类型type：SessionType.C2C
I/flutter (12706): 已添加会话id:18745043399,会话类型type：SessionType.C2C
I/flutter (12706): 已添加会话id:@TGS#2QVKBJHGN,会话类型type：SessionType.Group
```
build：log:
```
home页面listener被触发  --start---
I/flutter (15282): [Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity']
I/flutter (15282): 已添加会话id:null,会话类型type：null
I/flutter (15282): 已经存在，不添加该条会话id:null,会话类型type：null
I/flutter (15282): 已经存在，不添加该条会话id:null,会话类型type：null
I/flutter (15282): 已经存在，不添加该条会话id:null,会话类型type：null
```
`

**Comment by JiangJuHong** [comment]
我明白了，最近我会安排时间进行排查修复

**Comment by yuefeng007** [comment]
你好作者，debug版本也拿不到列表了。刚刚拉了  github 上最新demo 也是拿不到了！

**Comment by JiangJuHong** [comment]
你好，我今天测试的时候没有发现问题，你可以提供一个错误信息吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 峰硕 <notifications@github.com&gt;
发送时间: 2020年3月9日 20:51
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: 蒋具宏 <690717394@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 打包 apk后 得到的会话实体<SessionEntity&gt;，好像是有问题，我不太能确定是否是我的问题！ (#3)




你好作者，debug版本也拿不到列表了。刚刚拉了  github 上最新demo 也是拿不到了！

**Comment by yuefeng007** [comment]
没有错误信息，就是没会话。还是这个方法
监听器只被触发了一次 ，是这个类型`ListenerTypeEnum.Connected`
```
 TencentImPlugin.addListener((type,params){
   if (type == ListenerTypeEnum.RefreshConversation) {

   }
});
```

**Comment by yuefeng007** [comment]
```
I/flutter (22408): IM初始化成功
I/flutter (22408): _listener监听器被触发  --start---
I/flutter (22408): 监听到未处理类型 ListenerTypeEnum.Connected
I/flutter (22408): 监听到未处理参数null
I/flutter (22408): _listener监听器被触发 --end---
I/flutter (22408): im登录成功
```

**Comment by yuefeng007** [comment]
测试账号列表里一共有4条会话，上午的时候我就发现有问题。仅返回一条会话。后来下午一条会话都获取不到了

**Comment by JiangJuHong** [comment]
好的，我会尝试复现这个问题，感谢你的反馈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 峰硕 <notifications@github.com&gt;
发送时间: 2020年3月9日 21:13
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: 蒋具宏 <690717394@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 打包 apk后 得到的会话实体<SessionEntity&gt;，好像是有问题，我不太能确定是否是我的问题！ (#3)




测试账号列表里一共有4条会话，上午的时候我就发现有问题。仅返回一条会话。后来下午一条会话都获取不到了

**Comment by yuefeng007** [comment]
感谢作者。静候佳音

**Comment by JiangJuHong** [comment]
我在本地环境测试没有发现问题，你可以提供一下复现代码吗？

**Comment by JiangJuHong** [comment]
你使用的版本号是多少？

**Comment by yuefeng007** [comment]
最新的 0.1.17.稍等  我在拉下demo试试

**Comment by yuefeng007** [comment]
抱歉，好像是我们服务端的 问题，我用您的demo 登录我们自己的im 是登录不上的，有报错信息。

```
E/flutter ( 6709): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(70003, Execution Error, tlssdk Unpack error)
E/flutter ( 6709): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6709): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 6709): <asynchronous suspension>
E/flutter ( 6709): #2      TencentImPlugin.login (package:tencent_im_plugin/tencent_im_plugin.dart:43:10)
E/flutter ( 6709): #3      LoginPageState.onLogin (package:tencent_im_plugin_example/main.dart:43:21)
E/flutter ( 6709): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 6709): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 6709): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6709): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6709): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6709): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 6709): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter ( 6709): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 6709): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 6709): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 6709): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 6709): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 6709): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 6709): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6709): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6709): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6709): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6709): #21     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6709): #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6709): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6709): #24     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 6709): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 6709):
```

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/76272221-c01dc300-62b5-11ea-8eee-e6dfc4246ec7.png)
7003 在腾讯云对应的是校验失败，请检查你的 identifier 和 userSig

**Comment by yuefeng007** [comment]
嗯嗯，刚才是我发错了。是我用过时的 userSig 在demo尝试登录。这会在您的demo上使用我们自己的im信息已经登录成功 。但是依然没有回话。我不知道是我们服务端的问题 还是什么问题。。但是我使用您的im信息是正常获取回话的

**Comment by JiangJuHong** [comment]
请确保 Console 是否有错误信息输出，或尝试使用 腾讯云 SDK 所提供的Demo查看会话

**Comment by yuefeng007** [comment]
没有任何错误输出信息，我在具体确定一下问题吧，确定好后 回复您

**Comment by yuefeng007** [comment]
我又新建了  几个会话，正常查出来了。。不知道之前的会话为什么没有了，可能是我们服务端那边调试了

**Comment by JiangJuHong** [comment]
好的，如果还有问题可以随时联系我

**Comment by yuefeng007** [comment]
谢谢  老哥，另外  打包apk后  会话实体数据里面的 属性都是null  。这个本周会排查修复好吗。

**Comment by JiangJuHong** [comment]
如果不出意外，它将在本周被修复

**Comment by yuefeng007** [comment]
好的 感谢。

**Comment by sunyaodong** [comment]
/Users/sunyd/Desktop/DevelopTool/flutter/.pub-cache/hosted/pub.flutter-io.cn/tencent_im_plugin-0.1.22/android/src/main/java/top/huic/tencent_im_plugin/TencentImPlugin.java:119: 错误: 无法访问LifecycleOwner
        final MethodChannel channel = new MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "tencent_im_plugin");
                                                                            ^
  找不到androidx.lifecycle.LifecycleOwner的类文件
注: /Users/sunyd/Desktop/DevelopTool/flutter/.pub-cache/hosted/pub.flutter-io.cn/tencent_im_plugin-0.1.22/android/src/main/java/top/huic/tencent_im_plugin/TencentImPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

大佬，我添加插件依赖后，运行，爆出这个错误。知道是什么原因吗？

**Comment by JiangJuHong** [comment]
你好，请问你是否执行了 Gradle Build。如果执行了，能否提供你的Flutter版本。且你有拉下Demo试运行吗？ @sunyaodong

**Comment by sunyaodong** [comment]
Gradle Build执行了。
Flutter版本1.9.1+hotfix.6 
我demo也报这个错误

**Comment by JiangJuHong** [comment]
你好，建议你先将Flutter升级为 stable 分支的最新版，然后再进行尝试。我在我的设备上没能复现这个问题。 @sunyaodong

**Comment by sunyaodong** [comment]
感谢大佬，我跑通了。问个问题identifier这个用户id去哪获取，还有userSig是密匙吗？ @JiangJuHong

**Comment by JiangJuHong** [comment]
@sunyaodong  这个identifier你可以自定义为任何值，建议关联到自己业务系统的用户唯一ID中，userSig是根据ID生成的密钥，腾讯云userSig生成相关文档：https://cloud.tencent.com/document/product/269/32688

**Comment by JiangJuHong** [comment]
这个问题已被修复，版本号为 0.2.0，问题原因是由于混淆配置不正确。 @yuefeng007 
0.2.0 已发布，地址:https://pub.dev/packages/tencent_im_plugin
由于版本改动较大，请根据 README.md 指引进行调整，感谢你的支持。

**Comment by yuefeng007** [comment]
好的。我现在去升级它。感谢作者，

**Comment by chinafelix** [comment]
[Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity', Instance of 'SessionEntity']

我调用TencentImPlugin.getConversationList()，返回以上的数据，这种数据是正常的吗？如果是，该格式怎么解析成json呢？

**Comment by yuefeng007** [comment]
> ['SessionEntity'的实例，'SessionEntity'的实例，'SessionEntity'的实例，'SessionEntity'的实例]
> 
> 我调用TencentImPlugin.getConversationList（），返回以上的数据，这种数据是正常的吗？如果是，该格式怎么解析成json呢？

不要解析成json。SessionEntity 是dart对象 可以直接访问其属性即可

**Comment by chinafelix** [comment]
@yuefeng007 你好，我对dart不太熟悉，方便说一下该怎么访问属性吗？
我参照session_entry.dart的结构，用以下方法获取faceUrl属性不行：
我用list[index]['faceUrl']访问不了；其中list是数组，list[index]是一个SessionEntity对象

**Comment by chinafelix** [comment]
你好，已经读取到属性值了；谢谢；
我们每次读取一个 ObjectEntry，都要找到对应的ObjectEntry对象，才能知道它里面包含哪些属性吗？

**Comment by yuefeng007** [comment]
我使用的是vscode 编辑器。按住ctrl键+鼠标左键点击要查看的dart类，直接跳转到 dart类声明位置就可以看到对象中的属性了&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午3:11
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"START"<551979197@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] 打包 apk后 得到的会话实体<SessionEntity&gt;，好像是有问题，我不太能确定是否是我的问题！ (#3)





 
你好，已经读取到属性值了；谢谢；
 我们每次读取一个 ObjectEntry，都要找到对应的ObjectEntry对象，才能知道它里面包含哪些属性吗？

**Comment by yuefeng007** [comment]
list[index]['faceUrl'] 这种可以访问json数据  ，dart对象要这样 list[index].faceUrl

**Comment by chinafelix** [comment]
谢谢，我用的AS编辑器，也可以的直接打开对应类的；

VSCode可以做到热更新吗？

**Comment by yuefeng007** [comment]
vscode&nbsp; 要手动按下R键。很快可以看到修改后的效果 。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午3:23
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"START"<551979197@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] 打包 apk后 得到的会话实体<SessionEntity&gt;，好像是有问题，我不太能确定是否是我的问题！ (#3)





 
谢谢，我用的AS编辑器，也可以的直接打开对应类的；
 
VSCode可以做到热更新吗？

**Comment by chinafelix** [comment]
学到了，我本来也想用vscode。但是没找到热更新的方法，才换了AS；

**Comment by yuefeng007** [comment]
vscode
obj. 的时候可以预览 当前obj可以访问的属性
类似这种







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午3:11
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"START"<551979197@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] 打包 apk后 得到的会话实体<SessionEntity&gt;，好像是有问题，我不太能确定是否是我的问题！ (#3)





 
你好，已经读取到属性值了；谢谢；
 我们每次读取一个 ObjectEntry，都要找到对应的ObjectEntry对象，才能知道它里面包含哪些属性吗？

**Comment by chinafelix** [comment]
这种只能正对Entry的对象吧；AS会有很多非属性的选项，所以不知道哪些是它的可访问属性，哪些不是

**Comment by chinafelix** [comment]
等下也换成vscode试试，比较顺手点
