### ISSUE TITLE
需要修改用户个人信息

### ISSUE THREAD

**Issue by mjl0602** [JiangJuHong/FlutterTencentImPlugin#30]
能封装相关方法吗，我看iOS与安卓的字段好像并不一样。

**Comment by JiangJuHong** [comment]
请参考 modifySelfProfile 接口

**Comment by mjl0602** [comment]
我已经看过这个接口与对应文档，然后在查看文档时发现iOS与安卓的key似乎并不相同。

// 参数，参见腾讯云修改自己资料文档 https://cloud.tencent.com/document/product/269/33926#.E4.BF.AE.E6.94.B9.E8.87.AA.E5.B7.B1.E7.9A.84.E8.B5.84.E6.96.99

我可能暂时不会用到这个功能，但是建议官方能作出封装，增强实用性。

**Comment by JiangJuHong** [comment]
字段请参考这个地址: [https://cloud.tencent.com/document/product/269/1500#.E6.A0.87.E9.85.8D.E8.B5.84.E6.96.99.E5.AD.97.E6.AE.B5](https://cloud.tencent.com/document/product/269/1500#.E6.A0.87.E9.85.8D.E8.B5.84.E6.96.99.E5.AD.97.E6.AE.B5)，不出意外，他们两个应该是通用的

**Comment by mjl0602** [comment]
感谢您的回答。这样应该是可以使用了。

这个库在将来有计划添加这部分的dart类封装吗

**Comment by JiangJuHong** [comment]
在未来版本会进行迭代，感谢你的支持

**Comment by mjl0602** [comment]
非常感谢如此及时的回复。
