### ISSUE TITLE
ios加入群组功能有bug

### ISSUE THREAD

**Issue by xjrad** [JiangJuHong/FlutterTencentImPlugin#31]
![image](https://user-images.githubusercontent.com/1243443/84125539-41c8ec80-aa6f-11ea-9b02-de9cbaf257b4.png)
![image](https://user-images.githubusercontent.com/1243443/84125648-6a50e680-aa6f-11ea-9489-e915906aae14.png)

native代码取ids参数
flutter 插件代码reason参数

导致一直报空指针错误

兄弟，尽快更新一个版本，不然后面的人要踩坑了

**Comment by JiangJuHong** [comment]
这个问题在 `0.2.32` 被修复
