### ISSUE TITLE
Regift.swift，有沒有其他視頻壓縮？

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#32]
flutter_video_compress，這個經常出錯
https://github.com/flutter/flutter/issues/37447

ios/Pods/Regift/Regift/Regift.swift:303:46: error: missing argument label 'preferredTimescale:' in call

**Comment by JiangJuHong** [comment]
视频压缩并不是唯一，你可以根据您的项目自行选定压缩组件，但是经过Flutter封装的压缩组件貌似不是很多。
