### ISSUE TITLE
提問initStorage？

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#33]
這個initStorage用途是？ 另外identifier 是否要跟login 的一樣？
    await TencentImPlugin.initStorage(identifier: "dev");

    await TencentImPlugin.login(
      identifier: "dev",
    ......
    );

我hot reload 時就卡在這句上

**Comment by JiangJuHong** [comment]
`initStorage` 是加载本地存储，如果它在 `login` 方法后执行，则永远不会运行通过!详细可参考腾讯云IM文档!

**Comment by JiangJuHong** [comment]
initStorage 和 login identifier 应该保持一致
