### ISSUE TITLE
IM.dart 新對話訊息沒法顯示

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#35]
IPHONE環境
 if (type == ListenerTypeEnum.NewMessages) {
//看語法理論上SetState 是可以，但是沒法更新，所以我加了這個強逼REFRESH，就顯示到新對話訊息，也能顯示出來，請問有沒有更好的方法？
       onRefresh();
      // 更新消息列表

      this.setState(()
      {
        data.add(DataEntity(data: params));

       // this.updateData(DataEntity(data: params));
        //data.add(DataEntity(data: params));

      });
      // 设置已读
      TencentImPlugin.setRead(sessionId: widget.id, sessionType: widget.type);

    }

**Comment by JiangJuHong** [comment]
你好，Demo只是IM插件接口使用的示例，其中可能存在很多不足，最终建议根据您的实际业务进行调整。当然，在插件完善后，如果有更多时间，我将会优化Demo和文档。

**Comment by shen-lan** [comment]
@wilson0506

试试 
```
       data.add(
          DataEntity(data: params[0]),
        );   
```
我遇到了一样的问题 。 这样写是没问题的
