### ISSUE TITLE
升级IM SDK版本?

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#36]
請問如何能幫上忙？

**Comment by JiangJuHong** [comment]
不是很明白您的意思，能否提供具体描述信息，并提供截图、Debug日志等内容

**Comment by wilson0506** [comment]
注意：由于腾讯云IM升级了新版本，但是本插件基于上一个版本，所以浏览开发文档时请通过以下地址：Android IOS ，在完成基本工作后，插件将进行相应更新

我想問如何能幫得上忙

**Comment by JiangJuHong** [comment]
您好，目前我了解的是腾讯云在新版本中增加了更加方便的方法。如果您有意向，可以在Flutter层次对方法进行增加，然后在Android、IOS层进行对应的实现，最后可以提交代码并请求PR，非常感谢您的贡献！
