### ISSUE TITLE
發圖會ERROR，紅畫面

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#37]

**Comment by JiangJuHong** [comment]
不是很明白您的意思，能否提供具体描述信息，并提供截图、Debug日志等内容

**Comment by wilson0506** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-20 at 21 03 39](https://user-images.githubusercontent.com/32795531/85202555-a4589d00-b339-11ea-99d0-b60141f3c49b.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-20 at 21 03 47](https://user-images.githubusercontent.com/32795531/85202557-a7ec2400-b339-11ea-8a65-81a3efa46f8f.png)

**Comment by JiangJuHong** [comment]
您好，第一幅图可能是Flutter 内部代码报错（布局、错误的方法调用 等），可以通过查看控制台日志获得更加详细的信息

**Comment by shenjingfs** [comment]
This error may happened after sending the image in the example

Error log:

```
The following NoSuchMethodError was thrown building:
The getter 'url' was called on null.
Receiver: null
Tried calling: url

im.dart (line 289):
return MessageImage(url: value.imageData[ImageType.Original].url);
```


This cause by value.node.imageData[ImageType.Original] passed by MessageEntity  is null when UploadProgress update

To solve it: 
change
`return MessageImage(url: value.imageData[ImageType.Original].url);`
to
`return MessageImage(url: value.imageData[ImageType.Original]?.url, path: value.path);`

**Comment by JiangJuHong** [comment]
感谢您的帮助，我会在下个版本修复它
