### ISSUE TITLE
SDKAppId

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#38]
騰訊雲裡OFFLINE PUSH設定時，要SKDAPPID，這個在那裡找

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/85370904-07c51380-b562-11ea-82a1-ecb7fa4b1842.png)
在这里

**Comment by wilson0506** [comment]
您上报的token不合法，请检查, 這個可以如何想

**Comment by JiangJuHong** [comment]
字面意思，Token非有效token

**Comment by wilson0506** [comment]
我剛在試FCM TOKEN，從FIREBASE拿下的TOKEN，上報用不了

**Comment by wilson0506** [comment]
在FIREBASE用這個TOKEN去推，能看到NOTIFICATION

**Comment by JiangJuHong** [comment]
我没有测试 FIREBASE Token，你可以检查一下是什么问题，欢迎回来反馈结果！感谢！

**Comment by wilson0506** [comment]
開了工單問QQ，但試不了什麼問題，正常拿了FCM TOKEN上報就可以
