### ISSUE TITLE
build android error

### ISSUE THREAD

**Issue by wilson0506** [JiangJuHong/FlutterTencentImPlugin#39]
早前試IOS，現在試ANDROID時，行不起來
==========================================================================
I/imsdk   (27177): TIM: ======  TIM
I/imsdk   (27177): TIM: ======  Ver: 4.6.1
I/imsdk   (27177): TIM: ======  Compile: Nov 13 2019 20:19:09
I/imsdk   (27177): TIM: ======  Platform: Android
I/imsdk   (27177): TIM: ======  PID: 27177
I/imsdk   (27177): TIM: ==========================================================================
D/imsdk   (27177): TIM: 2020-06-23 22:17:19.138/D/27177-27448   /Network   -looper_impl.cpp.195  operator()                            /looper start work|name:looper_logic
D/imsdk   (27177): TIM: 2020-06-23 22:17:19.145/D/27177-27449   /Network   -looper_impl.cpp.195  operator()                            /looper start work|name:looper_db
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.145/I/27177-27177   /Network   -imsession_sso_session.cpp.409  Init                        /session init, sdkAppId: 1400379445, system version: 10, app version: 4.6.1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.145/I/27177-27177   /Common    -imcore_manager.cpp.147  InitSdk                            /InitSdk, device type: CLT-L29, system version: 10, app version = 4.6.1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.145/I/27177-27448   /Network   -imsession_session_config.cpp.486  operator()               /read config file /data/user/0/com.example.test/files/imsdk_config
W/imsdk   (27177): TIM: 2020-06-23 22:17:19.145/W/27177-27448   /Network   -imsession_session_config.cpp.488  operator()               /cannot create config read stream
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.154/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.154/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.154/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.155/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/chatty  (27177): uid=10286(com.example.test) looper_log identical 1 line
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.155/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.156/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.156/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.158/I/27177-27448   /Network   -imsession_sso_session.cpp.925  MakesureConnect             /wait_connect_task_id_:0|interval: 0|netId:1:<unknown ssid>
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.159/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.159/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.159/I/27177-27177   /IMSDK     -BaseManager.0                                              /loadFriendshipModule init statt
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.162/I/27177-27177   /FriendShip-friendship_listener_jni.cpp.185  InitIDs                   /---- Start FriendshipListenerJni InitIDs
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.162/I/27177-27177   /FriendShip-friendship_listener_jni.cpp.212  InitIDs                   /---- End FriendshipListenerJni InitIDs
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.163/I/27177-27177   /FriendShip-friendship_jni.cpp.22  Java_com_tencent_imsdk_friendship_FriendshipNativeManager_nativeInitFriendshipModule/start init native Friendship Module
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.163/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.163/I/27177-27177   /Msg       -elem_processor.cpp.28  RegisterElemHandler                 /Register Elem Handler
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.164/I/27177-27177   /FriendShip-friendship_jni.cpp.34  Java_com_tencent_imsdk_friendship_FriendshipNativeManager_nativeInitFriendshipModule/end init native Friendship Module
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.165/I/27177-27177   /IMSDK     -TIMManager.0                                               /setUserConfig: userConfig=com.tencent.imsdk.TIMUserConfig@2179e90
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.165/I/27177-27177   /IMSDK     -imsdk.ConversationManager.0                                /addMessageListener: top.huic.tencent_im_plugin.listener.TencentImListener@9be9389
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.166/I/27177-27177   /IMSDK     -NetConnectInfoCenter.0                                     /network changed, action: android.net.conn.CONNECTIVITY_CHANGE
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.167/I/27177-27177   /IMSDK     -NetConnectInfoCenter.0                                     /wifi network connected
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.167/I/27177-27177   /IMSDK     -NetConnectInfoCenter.0                                     /current network: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.167/I/27177-27177   /Common    -manager_jni.cpp.273  Java_com_tencent_imsdk_manager_NativeManager_nativeOnNetworkChanged/OnNetworkChanged is connected 1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.169/I/27177-27177   /IMSDK     -NetConnectInfoCenter.0                                     /network changed, action: android.net.wifi.STATE_CHANGE
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.169/I/27177-27177   /IMSDK     -NetConnectInfoCenter.0                                     /network changed, action: android.net.wifi.WIFI_STATE_CHANGED
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /Network   -imsession_monitor.cpp.136  OnConnecting                    /previous record|content:date_time=1592921735&sdk_app_id=1400379445&conn_succ=1&conn_time=57&conn_last=207404&sdk_client_ip=&sso_ip=203.205.254.165&sso_port=8080&conn_reason=4&send_count=0&send_succ_count=0&send_high_count=0&send_high_succ_count=0&avg_rtt=0&net_type=wifi&state=1&timestamp=2020-06-23T22:15:35.340+0800&sso_ip_src=4&sso_ip_list=203.205.254.165:8080,203.205.253.149:8080&failed_ip_list=&error_code=0&reg_error_code=0&error_msg=
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /Network   -imsession_sso_session.cpp.962  NotifyNetState              /notify network change|status:0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /IMSDK     -NativeManager.0                                            /onNetworkStatusChanged Enter; type:2 code:0 errMsg:
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /IMSDK     -BaseManager.0                                              /onConnecting
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /Network   -imsession_sso_session.cpp.1493  DisableCheckNetwork        /check network stop
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.170/I/27177-27448   /Network   -imsession_session_config.cpp.123  GetSsoList               /netId:1:<unknown ssid>
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.176/I/27177-27448   /Network   -imsession_sso_session.cpp.783  operator()                  /OnDeviceNetworkChange|state:1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.176/I/27177-27448   /IMSDK     -NativeManager.0                                            /onNetworkStatusChanged Enter; type:2 code:0 errMsg:
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.176/I/27177-27448   /IMSDK     -BaseManager.0                                              /onConnecting
D/NetworkSecurityConfig(27177): No Network Security Config specified, using platform default
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.226/I/27177-27448   /Network   -imsession_session_config.cpp.166  operator()               /response:203.205.253.149;203.205.254.165|costTime:56
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.226/I/27177-27448   /Network   -imsession_sso_session.cpp.869  operator()                  /netType:1|netId:1:<unknown ssid>|ip count: 2|race:true|ssoListip_src:4
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.226/I/27177-27448   /Network   -imsession_sso_session.cpp.874  operator()                  /Ip list|ip:203.205.253.149|port:8080|weight:0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.226/I/27177-27448   /Network   -imsession_sso_session.cpp.874  operator()                  /Ip list|ip:203.205.254.165|port:8080|weight:0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.226/I/27177-27448   /Network   -imsession_sso_session.cpp.893  operator()                  /Connect begin, ip: 203.205.253.149, port: 8080
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.227/I/27177-27448   /Network   -channel.cpp.332  SetError                                  /channel error|id=0|error=0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.228/I/27177-27448   /Network   -imsession_sso_session.cpp.81  operator()                   /connect channelId: 0, status: 0, ec: 0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.228/I/27177-27448   /Network   -imsession_sso_session.cpp.96  operator()                   /Connecting, ip: 203.205.253.149, port: 8080, channel id: 0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.229/I/27177-27448   /Network   -imsession_sso_session.cpp.893  operator()                  /Connect begin, ip: 203.205.254.165, port: 8080
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.229/I/27177-27448   /Network   -channel.cpp.332  SetError                                  /channel error|id=1|error=0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.229/I/27177-27448   /Network   -imsession_sso_session.cpp.81  operator()                   /connect channelId: 1, status: 0, ec: 0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.229/I/27177-27448   /Network   -imsession_sso_session.cpp.96  operator()                   /Connecting, ip: 203.205.254.165, port: 8080, channel id: 1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.238/I/27177-27448   /Network   -imsession_sso_session.cpp.81  operator()                   /connect channelId: 0, status: 1, ec: 0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.239/I/27177-27448   /Network   -imsession_monitor.cpp.284  Record                          /record|content:date_time=1592921839&sdk_app_id=1400379445&conn_succ=1&conn_time=70&conn_last=0&sdk_client_ip=&sso_ip=203.205.253.149&sso_port=8080&conn_reason=0&send_count=0&send_succ_count=0&send_high_count=0&send_high_succ_count=0&avg_rtt=0&net_type=wifi&state=1&timestamp=2020-06-23T22:17:19.239+0800&sso_ip_src=4&sso_ip_list=203.205.253.149:8080,203.205.254.165:8080&failed_ip_list=&error_code=0&reg_error_code=0&error_msg=
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.239/I/27177-27448   /Network   -imsession_sso_session.cpp.128  operator()                  /Connected succeed, ip: 203.205.253.149, port: 8080, channel id: 0, failed ip list: 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.239/I/27177-27448   /Network   -imsession_sso_session.cpp.962  NotifyNetState              /notify network change|status:1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.239/I/27177-27448   /IMSDK     -NativeManager.0                                            /onNetworkStatusChanged Enter; type:1 code:0 errMsg:
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.239/I/27177-27448   /IMSDK     -BaseManager.0                                              /onConnected
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.240/I/27177-27448   /Network   -imsession_sso_session.cpp.930  SendRemain                  /send remain|size: 0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.240/I/27177-27448   /Network   -imsession_sso_session.cpp.952  SendRemain                  /send cache|size: 0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.240/I/27177-27448   /Network   -imsession_sso_session.cpp.1493  DisableCheckNetwork        /check network stop
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -imsession_sso_session.cpp.1458  EnableCheckNetwork         /check network start, current netId: 1:<unknown ssid>
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -imsession_sso_session.cpp.81  operator()                   /connect channelId: 1, status: 1, ec: 0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -imsession_sso_session.cpp.110  operator()                  /Connected later, ip: 203.205.254.165, port: 8080, channel id: 1
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -channel.cpp.293  Close                                     /channel closing
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -imsession_sso_session.cpp.81  operator()                   /connect channelId: 1, status: 2, ec: 0, 
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.250/I/27177-27448   /Network   -channel.cpp.172  OnChannelRecycle                          /channel recycle|id:1|count:0
I/imsdk   (27177): TIM: 2020-06-23 22:17:19.628/I/27177-27446   /IMSDK     -SessionWrapper.0                                           /try to bind service,

**Comment by JiangJuHong** [comment]
能否提供完整的错误信息以及复现步骤(或触发条件)，这有助于排查错误

**Comment by wilson0506** [comment]
搞了2小時，成功FCM ANDROID，不過FCM IOS 還要努力

另外，有計麼情況下會有到OFFLINE PUSH？

沒開APP下傳訊息給用戶？（這個目前未看到PUSH）
＝＝＝＝＝＝

成功推送。如果仍无法接收，请确认接收方手机已经打开您APP的通知功能并检查手机是否与谷歌推送服务器保持连接。 检查手机是否与谷歌推送服务器保持连接的参考文档: https://firebase.google.com/support/troubleshooter/fcm/delivery/diagnose/android

**Comment by JiangJuHong** [comment]
感谢您的帮助和回馈！
