### ISSUE TITLE
作者你好。我这有个关于视频消息的疑问！

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#4]
当我收到视频消息时，我尝试输出《NodeVideoEntity》里面的属性如下：
我注意到缩略图 和视频路径  都是一样的。这块我应该如何使用呢
```
I/flutter (30266): =============snapshot(缩略图)=================
I/flutter (30266): ***snapshotPath***
I/flutter (30266): /storage/emulated/0/Android/data/****包名不可见***/files/Pictures
I/flutter (30266): ***snapshotInfo.size***
I/flutter (30266): 0
I/flutter (30266): ***snapshotInfo.width***
I/flutter (30266): 640
I/flutter (30266): ***snapshotInfo.height***
I/flutter (30266): 360
I/flutter (30266): =============snapshot(视频)=================
I/flutter (30266): ***videoPath***
I/flutter (30266): /storage/emulated/0/Android/data/****包名不可见***/files/Pictures
I/flutter (30266): ***videoInfo.duaration***
I/flutter (30266): 10
I/flutter (30266): ***videoInfo.size***
I/flutter (30266): 0
I/flutter (30266): ***videoInfo.type***
I/flutter (30266): mp4
I/flutter (30266): ***videoInfo.uuid***
I/flutter (30266):
I/flutter (30266): ***taskId***
I/flutter (30266): 0
```

**Comment by JiangJuHong** [comment]
你是否有查看他们类型是否一致，都是mp4或其中包含一个 jpg 图像信息

**Comment by yuefeng007** [comment]
是的，我上传的视频是mp4。缩略图是png的
上传时参数如下：
```
path:《 /storage/emulated/0/DCIM/Camera/VID20200303204557.mp4》
type:《mp4》
snapshotPath:《/storage/emulated/0/DCIM/Screenshots/Screenshot_2020-03-12-18-50-55-54.png》
snapshotWidth:《640》
snapshotHeight《360》
duration:《10》
```

**Comment by JiangJuHong** [comment]
他们使用的时候，缩略图当做封面即可。

**Comment by yuefeng007** [comment]
现在我主要的困惑是  ，得到的这个路径《/storage/emulated/0/Android/data/****包名不可见***/files/Pictures》 缩略图 和视频的地址是一样的,我比较疑问 正确返回就是这样的吗？
另外 我直接只用返回的路径给播放器  ，播放器是不能正常工作的
直接使用 VideoPlayer插件的 如下方法 是不能播放的
```
VideoPlayerController.file(File(widget.filePath))..initialize().then((_) {
        _controller.play();
        _controller.setLooping(true);
        setState(() {});
      });
```

**Comment by JiangJuHong** [comment]
近期我会在Demo增加视频预览，供你参考

**Comment by yuefeng007** [comment]
感谢作者

**Comment by yuefeng007** [comment]
大佬，我搞明白了，方法返回的路径是可以直接用的，之前播放器无法正常工作是因为我的网络不好，视频没有下载完成。另外我想问个问题。是所有的视频都会主动下载吗，如果比较大的视频文件是否需要用户主动触发下载方法。方便的话可以和我说下大概思路吗

**Comment by yuefeng007** [comment]
还有就是下载进度这块是否有方法监听

**Comment by JiangJuHong** [comment]
你好，我正在进行的0.2.0版本升级工作就包含将视频下载公布到Flutter层，届时所有视频下载都将可控。由于0.2.0与以前代码不兼容，所以升级时请根据文档指引。


0.2.0将在近期发布，请随时关注。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 峰硕 <notifications@github.com&gt;
发送时间: 2020年3月14日 22:33
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: 蒋具宏 <690717394@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 作者你好。我这有个关于视频消息的疑问！ (#4)





 
大佬，我搞明白了，方法返回的路径是可以直接用的，之前播放器无法正常工作是因为我的网络不好，视频没有下载完成。另外我想问个问题。是所有的视频都会主动下载吗，如果比较大的视频文件是否需要用户主动触发下载方法。方便的话可以和我说下大概思路吗
