### ISSUE TITLE
native模型与flutter模型参数不一致

### ISSUE THREAD

**Issue by ligui-iOS** [JiangJuHong/FlutterTencentImPlugin#40]
GroupPendencyEntity这个模型中，swift：handlerStatus，flutter：handledStatus造成getGroupPendencyList此方法返回的数据中handledStatus为null，麻烦作者改一下，谢谢！

**Comment by ligui-iOS** [comment]
大佬 我提交了pull request

**Comment by JiangJuHong** [comment]
我已完成合并，并发布 0.2.34
