### ISSUE TITLE
实际接入时建议(随时补充)

### ISSUE THREAD

**Issue by lhalcyon** [JiangJuHong/FlutterTencentImPlugin#42]
首先感谢作者封装插件供开发者使用!

在实际接入中遇到一些实际问题
1. login  接口无法知道是否登录回调结果. 返回值是 Future<void> . 很容易造成IM未登录,却继续处理之后的逻辑
2. 建议封装下 getLoginStatus() 接口 , 若已经是登录状态,再次调取登录会报错 , 但是由于1.的问题无法显式甄别错误
3. getConversationList 接口建议提供分页封装 , 否则数据量大的情况容易出错
... TODO 补充

**Comment by JiangJuHong** [comment]
你好，以下是依次对应问题的回答：
    1. login 接口正常执行则代表登录成功，异常则代表失败。如果需要等待执行结束后执行其它代码，请使用  await
    2. getLoginStatus() 可通过 getLoginUser 进行判断，如果 `getLoginUser` 返回的是 null，则代表未登录
    3. 本插件只是基于腾讯云IM进行封装，当前集成的SDK版本在 `getConversationList` 接口上不支持分页，所以我们插件层次没有办法进行“伪分页”

感谢您的建议，欢迎您随时补充！

**Comment by MrshawY** [comment]
你好，使用插件后遇到的问题
第一次登录之后,退出。下次登录需不需要初始话？需要初始滑的时候，发送方发一条消息，接收方就会收到多条消息，多条消息的数量在与你登录登出的次数(登出的时候使用了removeListener).如果仅仅只需要第一次登录初始化的话，登出之后在进行登录，监听器监听不到任何数据

**Comment by JiangJuHong** [comment]
该问题将会被关闭，如果您有其它疑问，请创建新 lssues，该 lssues 下的内容将不再做回复.
