### ISSUE TITLE
关于上传到 app store 的问题 

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#47]
app 构建版本上传至app store 时 苹果提示相关推送权限的问题
我想可能是im插件的关系，如果我不打算使用推送，是否可以通过一些简单的修改后 正常上传至 app atore呢
`ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.`

**Comment by JiangJuHong** [comment]
您好，相关推送权限需要在您项目中的 `Info.plist` 中进行设置，如果您不打算使用推送权限，在 Info.plist 中移除推送相关权限即可. 该插件不会干扰您的任何权限设置，权限控制以您的主项目为主!

**Comment by yuefeng007** [comment]
感谢

**Comment by JiangJuHong** [comment]
该插件只是基于原生SDK进行封装，如果原生SDK会进行通知权限注册，那么请咨询腾讯IM工单. 本插件没有对权限进行任何控制!
