### ISSUE TITLE
你好，createGroup接口可以加上自定义数据的参数吗

### ISSUE THREAD

**Issue by yohom** [JiangJuHong/FlutterTencentImPlugin#48]
参考 Android: https://cloud.tencent.com/document/product/269/9236#.E5.88.9B.E5.BB.BA.E7.BE.A4.E7.BB.84 iOS:https://cloud.tencent.com/document/product/269/9152#.E5.88.9B.E5.BB.BA.E6.8C.87.E5.AE.9A.E5.B1.9E.E6.80.A7.E7.BE.A4.E7.BB.84
另外V2版本的createGroup接口我貌似没有发现自定义数据的参数，不知道你那边怎么看？是移到别的地方去了吗？

**Comment by JiangJuHong** [comment]
目前创建群组不支持自定义信息，可能是我疏忽了，我将在下个版本进行添加，如果你急用，建议你使用 createGroup 后，通过 
 modifyGroupInfo 接口进行设置

**Comment by JiangJuHong** [comment]
它在 `0.2.36 ` 版本中被添加
