### ISSUE TITLE
华为推送flutter插件

### ISSUE THREAD

**Issue by dancebear** [JiangJuHong/FlutterTencentImPlugin#49]
发现了一个华为推送的flutter插件，请参考https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1

**Comment by JiangJuHong** [comment]
感谢！我会尝试集成，并编写接入文档！

**Comment by JiangJuHong** [comment]
华为离线推送插件已经集成到Demo，并已更新相应文档，请参考 [华为离线推送集成步骤](https://github.com/JiangJuHong/FlutterTencentImPlugin#%E5%8D%8E%E4%B8%BA-hua_wei_push_plugin--) 进行集成!
感谢您的帮助!
