### ISSUE TITLE
请问发送图片的逻辑是什么？

### ISSUE THREAD

**Issue by YDJSZY** [JiangJuHong/FlutterTencentImPlugin#53]
只是发送我本地图片的地址吗？那别人怎么显示这张图片？

**Comment by JiangJuHong** [comment]
请参考 `ImageMessageNode` 节点，最终你本地的图片会被上传到腾讯云服务器.
在你使用时，`ImageMessageNode` 节点会将图片的URL信息读取并返回给你

**Comment by YDJSZY** [comment]
`/// 选择图片
  onSelectImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      this.sendMessage(
        ImageMessageNode(
          path: image.path,
        ),
        MessageImage(
          path: image.path,
        ),
      );
    }
  }`
`/// 发送消息
  sendMessage(node, wd) {
    TencentImPlugin.sendMessage(
      sessionId: widget.id,
      sessionType: widget.type,
      node: node,
    ).then((res) {
      this.setState(() {
        this.updateData(DataEntity(data: res));
      });
    }).catchError((e) {
      _scaffoldKey.currentState
          .showSnackBar(SnackBar(content: new Text('消息发送失败:$e')));
    });
  }`
你这个wd好像没使用啊。

**Comment by JiangJuHong** [comment]
该参数为预留参数，原先意图为实现`发送中`内容回显功能，但是该方法暂未实现，故参数暂未使用.

**Comment by JiangJuHong** [comment]
如果您没有更多疑问，我将关闭此Issues
