### ISSUE TITLE
emoj

### ISSUE THREAD

**Issue by cnjsyyb** [JiangJuHong/FlutterTencentImPlugin#56]
这个有实现不

**Comment by JiangJuHong** [comment]
如果你打打算使用 emoji，可以通过以下方式：
1. 进入(https://emojixd.com/)[https://emojixd.com/]类似的 emoji 表情大全网站，导入表情到项目中，因为它本身是文本，所以可以通过Text组件发送
2. 通过Custom节点自定义表情节点，缺点是不能和文本字段混用

**Comment by cnjsyyb** [comment]
你们有具体实现的时间不？

**Comment by cnjsyyb** [comment]
大佬，这个有具体计划的时间不。本打算搞输入框插入图片。

**Comment by JiangJuHong** [comment]
你好，该插件目前不支持多节点发送，只能类似微信同时发送一个节点.
但是您说的 emoji ，因为本身就是文本，所以可以和文本共同输入.

**Comment by cnjsyyb** [comment]
微信输入框中[微笑]会显示出对应图片，这个会支持不

**Comment by JiangJuHong** [comment]
关于你说的这个问题有两种解决办法：
 1. 根据文本内容，在输入框显示文本字符，例如：  ` 测试内容[奸笑]1234`，然后在渲染的地方通过正则表达式进行替换，例如检测到 [奸笑] 则自动替换为表情库的表情（该种做法是推荐做法，也是目前微信的解决办法，这与插件本身没有关系，发送消息通过文本节点即可，解析时只需要解析文本字符串）
 2. 通过多节点插入，将表情单独为一个节点，当用户混入表情和文本时，则会使用到多个节点，该办法该插件目前不支持，具体支持计划未知，因为这个需求会引发很多问题

**Comment by JiangJuHong** [comment]
如果没有更多疑问，这个问题将会被关闭.
