### ISSUE TITLE
Unhandled Exception: PlatformException(6008, Execution Error, File upload failed: status code = 400)

### ISSUE THREAD

**Issue by YDJSZY** [JiangJuHong/FlutterTencentImPlugin#57]
发送图片时会报错，但之后重新获取聊天信息时能正常显示图片

**Comment by YDJSZY** [comment]
选择图片代码如下：
`selectImage(bool enableCamera) async {
    try {
      var resultList = await MultiImagePicker.pickImages(
        maxImages: enableCamera ? 1 : 9,
        enableCamera: enableCamera,
        cupertinoOptions: CupertinoOptions(
          selectionFillColor: "#ff11ab",
          selectionTextColor: "#ffffff",
          selectionCharacter: "✓",
        ),
        materialOptions: MaterialOptions(
            actionBarColor: "#abcdef",
            actionBarTitle: "Example App",
            allViewTitle: "所有照片",
            useDetailsView: false,
            selectCircleStrokeColor: "#000000",
            okButtonDrawable: '好的'),
      );
      resultList.forEach((element) async {
        var name = element.name;
        final imageByteData = await element.getByteData();
        String dir = (await getTemporaryDirectory()).path;
        File file = new File('$dir/$name');
        File res = await file.writeAsBytes(imageByteData.buffer.asInt8List());
        String imgPath = res.uri.toString().split('file://')[1];
        TencentImPlugin.sendMessage(
          sessionId: widget.imTarget['name'],
          sessionType: SessionType.C2C,
          node: ImageMessageNode(path: imgPath)
        );
      });
    } on Exception catch (e) {}
  }`

**Comment by YDJSZY** [comment]
选择图片代码：
`
selectImage(bool enableCamera) async {
    try {
      var resultList = await MultiImagePicker.pickImages(
        maxImages: enableCamera ? 1 : 9,
        enableCamera: enableCamera,
        cupertinoOptions: CupertinoOptions(
          selectionFillColor: "#ff11ab",
          selectionTextColor: "#ffffff",
          selectionCharacter: "✓",
        ),
        materialOptions: MaterialOptions(
            actionBarColor: "#abcdef",
            actionBarTitle: "Example App",
            allViewTitle: "所有照片",
            useDetailsView: false,
            selectCircleStrokeColor: "#000000",
            okButtonDrawable: '好的'),
      );
      resultList.forEach((element) async {
        var name = element.name;
        final imageByteData = await element.getByteData();
        String dir = (await getTemporaryDirectory()).path;
        File file = new File('$dir/$name');
        File res = await file.writeAsBytes(imageByteData.buffer.asInt8List());
        String imgPath = res.uri.toString().split('file://')[1];
        TencentImPlugin.sendMessage(
          sessionId: widget.imTarget['name'],
          sessionType: SessionType.C2C,
          node: ImageMessageNode(path: imgPath)
        );
      });
    } on Exception catch (e) {}
  }
`

**Comment by YDJSZY** [comment]
selectImage(bool enableCamera) async {
    try {
      var resultList = await MultiImagePicker.pickImages(
        maxImages: enableCamera ? 1 : 9,
        enableCamera: enableCamera,
        cupertinoOptions: CupertinoOptions(
          selectionFillColor: "#ff11ab",
          selectionTextColor: "#ffffff",
          selectionCharacter: "✓",
        ),
        materialOptions: MaterialOptions(
            actionBarColor: "#abcdef",
            actionBarTitle: "Example App",
            allViewTitle: "所有照片",
            useDetailsView: false,
            selectCircleStrokeColor: "#000000",
            okButtonDrawable: '好的'),
      );
      resultList.forEach((element) async {
        var name = element.name;
        final imageByteData = await element.getByteData();
        String dir = (await getTemporaryDirectory()).path;
        File file = new File('$dir/$name');
        File res = await file.writeAsBytes(imageByteData.buffer.asInt8List());
        String imgPath = res.uri.toString().split('file://')[1];
        TencentImPlugin.sendMessage(
          sessionId: widget.imTarget['name'],
          sessionType: SessionType.C2C,
          node: ImageMessageNode(path: imgPath)
        );
      });
    } on Exception catch (e) {}
  }

**Comment by YDJSZY** [comment]
选择图片代码：
selectImage(bool enableCamera) async {
    try {
      var resultList = await MultiImagePicker.pickImages(
        maxImages: enableCamera ? 1 : 9,
        enableCamera: enableCamera,
        cupertinoOptions: CupertinoOptions(
          selectionFillColor: "#ff11ab",
          selectionTextColor: "#ffffff",
          selectionCharacter: "✓",
        ),
        materialOptions: MaterialOptions(
            actionBarColor: "#abcdef",
            actionBarTitle: "Example App",
            allViewTitle: "所有照片",
            useDetailsView: false,
            selectCircleStrokeColor: "#000000",
            okButtonDrawable: '好的'),
      );
      resultList.forEach((element) async {
        var name = element.name;
        final imageByteData = await element.getByteData();
        String dir = (await getTemporaryDirectory()).path;
        File file = new File('$dir/$name');
        File res = await file.writeAsBytes(imageByteData.buffer.asInt8List());
        String imgPath = res.uri.toString().split('file://')[1];
        TencentImPlugin.sendMessage(
          sessionId: widget.imTarget['name'],
          sessionType: SessionType.C2C,
          node: ImageMessageNode(path: imgPath)
        );
      });
    } on Exception catch (e) {}
  }

**Comment by JiangJuHong** [comment]
根据文件提示是文件上传失败，请参考腾讯云IM错误码说明: https://cloud.tencent.com/document/product/269/1671

**Comment by YDJSZY** [comment]
我知道是图片上传失败。我用的是multi_image_picker插件。然后换成image_picker跟你的例子一样也报这个错

**Comment by JiangJuHong** [comment]
请切换图片或更换设备后进行尝试

**Comment by YDJSZY** [comment]
真机也试了，还是一样，第一次发送图片就报错，重新进聊天界面图片又能正常显示

**Comment by JiangJuHong** [comment]
是在Demo中出现该情况的吗？我在实际使用中没能复现这个问题

**Comment by YDJSZY** [comment]
是在我自己的代码中。奇怪了。

**Comment by JiangJuHong** [comment]
0.0  可能存在图片或权限问题，可以从这个方向排查下

**Comment by YDJSZY** [comment]
在真机能发送成功，不显示是因为我没监听UploadProgress事件。

**Comment by JiangJuHong** [comment]
监听过后就没有异常了吗？

**Comment by YDJSZY** [comment]
真机可以。模拟器可能是你说的权限问题。发送图片都是6008

**Comment by JiangJuHong** [comment]
可能就是权限问题，可以再检查下
