### ISSUE TITLE
TencentImPlugin.deleteConversation 返回null

### ISSUE THREAD

**Issue by YDJSZY** [JiangJuHong/FlutterTencentImPlugin#58]
删除会话TencentImPlugin.deleteConversation返回null，但实际已经删除成功了。

**Comment by JiangJuHong** [comment]
IOS 设备会一直返回NULL，它将在下个版本被修复

**Comment by JiangJuHong** [comment]
这个问题在 `0.2.41` 被修复

**Comment by YDJSZY** [comment]
ok!谢谢！还有个问题麻烦下。A删除了跟B的会话后，B再给A发消息，A还能收到以前的消息记录。删除会话没把聊天记录一同删掉吗

**Comment by JiangJuHong** [comment]
如果您需要删除本地聊天记录，请调用 `deleteLocalMessage` 接口

**Comment by JiangJuHong** [comment]
腾讯云IM SDK 暂不支持删除远程聊天记录，仅支持删除本地聊天记录. 感谢您的支持

**Comment by YDJSZY** [comment]
腾讯Im的锅啊，好吧。这个有点坑。。。谢谢！

**Comment by YDJSZY** [comment]
我看腾讯im文档，删除会话时应该是可以删除聊天记录的。[https://cloud.tencent.com/document/product/269/9232#.E5.88.A0.E9.99.A4.E4.BC.9A.E8.AF.9D](url)

**Comment by JiangJuHong** [comment]
> 腾讯云IM SDK 暂不支持删除远程聊天记录，仅支持删除本地聊天记录. 感谢您的支持



> 如果您需要删除本地聊天记录，请调用 `deleteLocalMessage` 接口，或使用 `deleteConversation` 接口传递 `removeCache:true` 参数

可以删除，但是只能删除本地消息，请参考如上两个回答

**Comment by JiangJuHong** [comment]
引用腾讯云文档:
````
删除本地消息的情况下，C2C 会话将无法获取到删除会话前的历史消息。
删除本地消息的情况下，群组会话通过 getMessage 仍然会拉取到漫游消息，所以存在删除消息成功，但是拉取消息的时候仍然获取到删除会话前的历史消息的情况，取决于是否重新从漫游拉回到本地。如果不需要拉取漫游，可以通过 getLocalMessage 获取消息，或者只通过 getMessage 拉取指定条数（如未读条数数量）的消息。
````

**Comment by YDJSZY** [comment]
对呀，删除本地消息的情况下，C2C 会话将无法获取到删除会话前的历史消息。我现在还能获取到。。。为啥

**Comment by YDJSZY** [comment]
deleteConversation(String id, SessionType type, int index) async {
    bool res = await TencentImPlugin.deleteConversation(
      sessionId: id, 
      sessionType: type,
      removeCache: true
    );
    await TencentImPlugin.deleteLocalMessage(sessionId: id, sessionType: type);
    if (res) {
      setState(() {
        conversationList.removeAt(index);
      });
    }
  }

**Comment by JiangJuHong** [comment]
Android底层实现如下:
````java
        if (removeCache) {
            res = TIMManager.getInstance().deleteConversationAndLocalMsgs(sessionType, sessionId);
        } else {
            res = TIMManager.getInstance().deleteConversation(sessionType, sessionId);
        }
````
请仔细检查业务代码. 以及获得消息聊天记录的代码.

**Comment by JiangJuHong** [comment]
我在IOS设备上测试线上项目，发现：
`C2C 删除会话后重新创建会话，不会获得之前的历史记录.`
请仔细检查您的业务代码.

**Comment by YDJSZY** [comment]
我是A删除跟B的会话，然后B并没有删除跟A的会话，B再给A发消息。发现A执行TencentImPlugin.getMessages获取到的还包括之前的消息。ios模拟器和iphone测试

**Comment by JiangJuHong** [comment]
相同测试，问题复现，移至问题 #60
