### ISSUE TITLE
最新版本报错

### ISSUE THREAD

**Issue by YDJSZY** [JiangJuHong/FlutterTencentImPlugin#59]
tencent_im_plugin-0.2.41/ios/Classes/SwiftTencentImPlugin.swift:722:52: error: optional type 'Bool?'
    cannot be used as a boolean; test for '!= nil' instead
                    res = TIMManager.sharedInstance()?.delete(TIMConversationType(rawValue: SessionType.getEnumByName(name: sessionTypeStr)!.rawValue)!, receiver: sessionId);
                                                       ^
                          ((                                                                                                                                                 )
                          != nil)

**Comment by JiangJuHong** [comment]
感谢您的反馈，我将尽快修复它

**Comment by JiangJuHong** [comment]
在 `0.2.42` 解决了此问题
