### ISSUE TITLE
删除会话消息后，通过getMessage依旧能获得历史消息 

### ISSUE THREAD

**Issue by JiangJuHong** [JiangJuHong/FlutterTencentImPlugin#61]
我是A删除跟B的会话，然后B并没有删除跟A的会话，B再给A发消息。发现A执行TencentImPlugin.getMessages获取到的还包括之前的消息。ios模拟器和iphone测试

_Originally posted by @YDJSZY in https://github.com/JiangJuHong/FlutterTencentImPlugin/issues/58#issuecomment-659219325_

**Comment by iyuhang** [comment]
TencentImPlugin.deleteConversation(sessionId: sessionEntity.id, sessionType: sessionType, removeCache: true);

removeCache 设置了吧

**Comment by JiangJuHong** [comment]
引用最新版SDK的文档描述：(文档地址)[https://cloud.tencent.com/document/product/269/44492#.E5.88.A0.E9.99.A4.E4.BC.9A.E8.AF.9D]
````
调用 deleteConversation 接口可以删除某个会话，会话删除不支持多端同步，删除会话时默认删除本地历史消息。
仅支持删除本地历史消息，不支持删除云端的历史消息，如果删除的会话重新激活，仍可以从云端拉取到该会话的历史消息。
````

**Comment by JiangJuHong** [comment]
初步猜测：腾讯云IM新版SDK更新了服务端，已禁用删除服务端会话.
如果是此原因造成，后续该插件中也会相应进行禁止.

**Comment by JiangJuHong** [comment]
参考文档1: 
会话删除(https://cloud.tencent.com/document/product/269/44492#.E5.88.A0.E9.99.A4.E4.BC.9A.E8.AF.9D)
参考文档2: 
消息删除(https://cloud.tencent.com/document/product/269/44489#.E5.88.A0.E9.99.A4.E4.BA.91.E7.AB.AF.E6.B6.88.E6.81.AF)

问题造成原因：腾讯云IM SDK升级，禁止删除云端消息，引入官方原话
````
目前暂不支持删除云端的消息，删除消息会导致云端建立反向映射关系，影响系统整体性能。
````

该问题将会被关闭，该插件将会在 升级SDK版本后进行兼容支持.

**Comment by YDJSZY** [comment]
这就尴尬了。测试和产品肯定会认为是bug的。哪有不能删除聊天记录的。官方也是坑

**Comment by JiangJuHong** [comment]
可是使用 getLocalMessage 代替 getMessage 缺点是换了设备后消息不同步

**Comment by JiangJuHong** [comment]
以微信为例，应该就是用的getLocalMessage，删除会话或更换设备后均不能获得历史记录.

**Comment by YDJSZY** [comment]
好像也对
