### ISSUE TITLE
您好，我遇到一个问题

### ISSUE THREAD

**Issue by abner-hello-world** [JiangJuHong/FlutterTencentImPlugin#62]
您好，已经解决了，是我自己的问题

**Comment by JiangJuHong** [comment]
好的，我将关闭该问题.

**Comment by abner-hello-world** [comment]
您好，
关于语音消息发送我遇到一个问题，路径都没有问题发送也成功了，可以接收消息端显示path为空，是怎么回事啊？
感谢大佬


| |
张涛
|
|
abner_hello_world@163.com
|
签名由网易邮箱大师定制


在2020年07月29日 13:13，蒋具宏<notifications@github.com> 写道：

Closed #62.
