### ISSUE TITLE
您好，我在语音这边接收到的path始终为空

### ISSUE THREAD

**Issue by abner-hello-world** [JiangJuHong/FlutterTencentImPlugin#63]
![image](https://user-images.githubusercontent.com/16556439/88777961-737e4a00-d1ba-11ea-8553-a83e1f26e3b6.png)
，语音发送显示成功了，路径也没有问题，发送端播放也没问题。就是接收端path为空，两部手机都是android手机

**Comment by JiangJuHong** [comment]
你好，语音、视频、视频缩略图，path只会在发送方被填充，接收方需要单独调用以下额外方法：
![image](https://user-images.githubusercontent.com/17740963/88778285-e982b100-d1ba-11ea-9c77-7674f793acd4.png)

**Comment by abner-hello-world** [comment]
好的，感谢感谢


| |
张涛
|
|
abner_hello_world@163.com
|
签名由网易邮箱大师定制


在2020年07月29日 16:46，蒋具宏<notifications@github.com> 写道：

你好，语音、视频、视频缩略图，path只会在发送方被填充，接收方需要单独调用以下额外方法：

**Comment by abner-hello-world** [comment]
> 你好，语音、视频、视频缩略图，path只会在发送方被填充，接收方需要单独调用以下额外方法：
> ![image](https://user-images.githubusercontent.com/17740963/88778285-e982b100-d1ba-11ea-9c77-7674f793acd4.png)

好的，感谢
