### ISSUE TITLE
关于图片这里有个问题

### ISSUE THREAD

**Issue by InTheClodus** [JiangJuHong/FlutterTencentImPlugin#64]
图片消息返回的url是只能用于下载,不能直接显示出来,不知道各位有没有遇到这样的问题
我这边返回图片url是这样的
(https://e5f6-1400403111-1256635546.cos.ap-shanghai.myqcloud.com/user2/73b25d276e3047f7e954c2c2e2168f2b.gif)
这个url测试过,不能直接显示,只能下载

**Comment by InTheClodus** [comment]
原因并非是这个url,这个url能正常显示. 今天做的时候跟着demo的聊天界面做的, demo里关于获取图片消息那里是这样写的:
```
        return MessageImage(
            url: value.imageData[ImageType.Thumb]?.url, path: value.path);
```
这里是同时获取了 url和path.然鹅:MessageImage是这样写的:

```
    return Container(
      height: 100,
      width: 100,
      child: path != null
          ? Image.file(
              File(path),
              fit: BoxFit.cover,
            )
          : url != null
              ? Image.network(
                  url,
                  fit: BoxFit.cover,
                )
              : Container(),
    );
```

如果path不为空显示path.否则才显示url的.但是上面这样一获取.这里的path就不会为空.在自己的机器能看到,但在其他机器就不行了. 所以把path: value.path删了就可以
找了好几个插件,还是这个写得比较完整.感谢作者大大的创造

**Comment by JiangJuHong** [comment]
这可能是demo的一个小BUG，非常抱歉给你带来的不便
