### ISSUE TITLE
视频下载监听返回数据不完整

### ISSUE THREAD

**Issue by MrshawY** [JiangJuHong/FlutterTencentImPlugin#65]
视频下载监听返回数据不完整  path路径返回只有一半 
并且缺少 currentSize 和 totalSize 字段 
![issues](https://user-images.githubusercontent.com/46661487/88893055-5d36c380-d278-11ea-92f3-9f4210af7b89.png)

**Comment by JiangJuHong** [comment]
这是由于使用 print 打印时只会打印限定长度的内容，超出内容将不会显示，请使用 Debug 模式进行调试
