### ISSUE TITLE
userSig过期重新登录问题

### ISSUE THREAD

**Issue by penghaihui** [JiangJuHong/FlutterTencentImPlugin#66]
我这边在userSig过期的时候重新登录，返回错误说已经登录，要先退出，但是退出的时候又返回错误说没有登录，但使用getLoginUser又能得到用户ID。

**Comment by JiangJuHong** [comment]
请提供您的代码信息或错误日志内容，以便有助于排查，谢谢!

**Comment by penghaihui** [comment]
userSig过期后重新登录，显示下面的错误


点击退出又提示下面的错误




&nbsp;getLoginUser接口又可以获取用户id




另外删除了监听器，然后退出app,重新进入重新监听，会发现监听的时候有新消息时执行了两次，再删除监听退出再进入，有新消息时就会执行三次。是不是SDK里面的监听器没有删除导致的，我看删除监听的时候只是对flutter部分的set进行了删除


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午4:17
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
请提供您的代码信息或错误日志内容，以便有助于排查，谢谢!

**Comment by JiangJuHong** [comment]
请提供您的代码信息

**Comment by JiangJuHong** [comment]
监听器请参考 #45

**Comment by penghaihui** [comment]
代码还是初始测试，有些乱，我是直接使用按钮执行登录，退出




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午5:05
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
请提供您的代码信息

**Comment by JiangJuHong** [comment]
请确认使用 await 同步块保证`login`或`logout`调用成功后再使用 `getLoginUser`

**Comment by penghaihui** [comment]
我就是通过 await 后获取的，登录只有userSig过期后会存在问题，不过期退出登录都没问题。我全程都是用按钮执行：初始化-登录-退出 还单独 两个添加监听 和移除监听，所以监听和取消监听没有自动添加的说法， 监听对象是静态方法，当我没退出app时，点击取消监听，然后发送信息是收不到，说明取消监听有效，但是退出重新进入后，添加一次监听，发送新信息就会出现执行了两次监听的方法，在取消监听退出，再进入就会三次 。。。 我测试了一下，并不是因为flutter这边存在多个监听器对象，而是安卓sdk源码那边存在多个监听，执行了多次请求flutter 。
import 'package:com_im/utils/im_utils.dart';
import 'package:com_im/utils/net_utils.dart';
import 'package:com_im/utils/rsa_utils.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  initApp();
}

void initApp()async {
  //runApp前执行一些操作


  await NetUtils.init();
  RsaUtils.init();
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() =&gt; _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage&gt; {
  int _counter = 0;
  @override
  void initState() {

    super.initState();


  }

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        actions: <Widget&gt;[
          IconButton(
            icon: Icon(Icons.adb),
            onPressed: ()async {
              await ImUtils.init();
            },
          ),
          IconButton(
            icon: Icon(Icons.account_box),
            onPressed: ()async {
              await ImUtils.login(context, '9');
            },
          ),
          IconButton(
            icon: Icon(Icons.account_circle),
            onPressed: ()async {
              ImUtils.onLogin(context,'9');
            },
          ),
          IconButton(
            icon: Icon(Icons.add_circle_outline),
            onPressed: ()async {
              ImUtils.addListener();
            },
          ),
          IconButton(
            icon: Icon(Icons.delete),
            onPressed: ()async {
              ImUtils.removeListener();
            },
          ),
          IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: ()async {
              await ImUtils.logout();
              await ImUtils.getLoginUser();
            },
          ),

        ],
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget&gt;[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午5:34
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
请确认使用 await 同步块保证login或logout调用成功后再使用 getLoginUser

**Comment by JiangJuHong** [comment]
监听问题请参考 #45 ，签名过期后登录报错请检查代码，其次可以在腾讯云提交工单.

**Comment by JiangJuHong** [comment]
腾讯云 im 的 init 方法，在app运行期间，仅允许调用一次

**Comment by JiangJuHong** [comment]
另外，如果需要进一步排查，代码请只贴出关键部分.  这样有助于快速排查.

**Comment by penghaihui** [comment]
是只运行一次。而且有做判断的。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;蒋具宏&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月31日(星期五) 晚上6:39
收件人:&nbsp;&quot;JiangJuHong/FlutterTencentImPlugin&quot;<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;&quot;penghaihui&quot;<313771130@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)

**Comment by JiangJuHong** [comment]
请贴出代码关键部分，以及你的设备信息、日志信息等内容

**Comment by penghaihui** [comment]
userSig过期后重新登录，
///登录，userSig过期执行此登录，
static Future<bool&gt; onLogin(ctx,String user)async{
  try {
    var res = await ImRepository.getSign(ctx, {});

    if (res.code == 0) {
      await TencentImPlugin.login(
        identifier: user,
        userSig: res.data,
      );
      return true;
    }
    return false;
  }catch(e){
      print(e);
      return false;

  }
}
显示下面的错误


点击退出
static void logout()async {
  try{
    await TencentImPlugin.logout();
  }catch(e){
    print(e);
    print('无用户登陆');
  }

}
提示下面的错误








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上9:33
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
请贴出代码关键部分，以及你的设备信息、日志信息等内容

**Comment by JiangJuHong** [comment]
抱歉，我没能看见完整的内容，您可以尝试登录网页版Github进行回复.
![image](https://user-images.githubusercontent.com/17740963/89041654-52fbee80-d378-11ea-9677-776e7694bd4c.png)

**Comment by penghaihui** [comment]
userSig过期后重新登录，
///登录，userSig过期执行此登录，
static Future<bool&gt; onLogin(ctx,String user)async{
  try {
    var res = await ImRepository.getSign(ctx, {});

    if (res.code == 0) {
      await TencentImPlugin.login(
        identifier: user,
        userSig: res.data,
      );
      return true;
    }
    return false;
  }catch(e){
      print(e);
      return false;

  }
}
显示下面的错误
PlatformException(login failed. , user is login ,user is already login,you should login out first)

点击退出
static void logout()async {
  try{
    await TencentImPlugin.logout();
  }catch(e){
    print(e);
    print('无用户登陆');
  }

}

显示如下错误
Logout failed , code -10001|descr
查了sdk错误代码，-10001属于腾讯云服务器返回代码 ：D2 过期。D2 是根据 UserSig 生成的内部票据，D2 的有效期小于或等于 UserSig 的有效期。请重新调用 TIMManager.getInstance().login 登录接口生成新的 D2。
 
我重新登录又显示上面登录的错误， TIMManager.getInstance().login 和  TIMManager.login 是不是同一个接口，

**Comment by JiangJuHong** [comment]
1. UserSig 过期为正常错误，当UserSig过期时，确实应该报改错，建议每次登录时都重新生成走后台生成UserSig
2. 如果UserSig过期导致登录失败，logout 返回未登录也是正确的
3. 如果UserSig过期导致登录失败，getLoginUser 返回null也是正确的

所有接口均是对腾讯云IM SDK进行封装，仅部分接口进行了特殊处理。

**Comment by penghaihui** [comment]
1、每次登录都是重新从后台获取新的userSig;
2、如果UserSig过期后使用TencentImPlugin.login重新登录失败，logout 返回的是D2过期，需要重新登录，但是使用插件重新登陆又返回已经登陆的错误，要先logout，这样就变成了死循环。
3、UserSig过期后，TencentImPlugin.getLoginUser&nbsp;返回的是实际登录用户的id，执行await&nbsp;TencentImPlugin.logout()后， 再次执行TencentImPlugin.getLoginUser&nbsp;返回的还是实际登录用户的id




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上11:54
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





  
UserSig 过期为正常错误，当UserSig过期时，确实应该报改错，建议每次登录时都重新生成走后台生成UserSig
 
如果UserSig过期导致登录失败，logout 返回未登录也是正确的
 
如果UserSig过期导致登录失败，getLoginUser 返回null也是正确的
  
所有接口均是对腾讯云IM SDK进行封装，仅部分接口进行了特殊处理。

**Comment by JiangJuHong** [comment]
UserSig过期后 如果您当前已经登录，则会保存。
建议您在每次登录和退出登录前  通过 getLoginUser 进行判断

**Comment by penghaihui** [comment]
我把原生代码TencentImPlugin.java里面的判断!TextUtils.isEmpty(TIMManager.getInstance().getLoginUser())注释掉过期时候就可以登录了
    /**
     * 腾讯云 IM 登录
     *
     * @param methodCall 方法调用对象
     * @param result     返回结果对象
     */
    private void login(MethodCall methodCall, final Result result) {
        // 用户ID和签名
        final String identifier = this.getParam(methodCall, result, "identifier");
        String userSig = this.getParam(methodCall, result, "userSig");

        // 如果用户已登录，则不允许重复登录
//        if (!TextUtils.isEmpty(TIMManager.getInstance().getLoginUser())) {
//            result.error("login failed. ", "user is login", "user is already login ,you should login out first");
//            return;
//        }

        // 登录操作
        TIMManager.getInstance().login(identifier, userSig, new VoidCallBack(result));
    }




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 凌晨1:02
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
UserSig过期后 如果您当前已经登录，则会保存。
 建议您在每次登录和退出登录前  通过 getLoginUser 进行判断

**Comment by JiangJuHong** [comment]
我将检查这个问题  如果是这个原因，我将进行修正.

**Comment by penghaihui** [comment]
我今天提交工单问了腾讯云：getLoginUser在userSig过期后不会返回用户id，但我这边测试了很多次，userSig过期后getLoginUser都还能获取到用户id，我觉得是他们接口有些问题。所以以getLoginUser作为判断是否登录依据不太准确。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;蒋具宏&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月1日(星期六) 晚上7:55
收件人:&nbsp;&quot;JiangJuHong/FlutterTencentImPlugin&quot;<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;&quot;penghaihui&quot;<313771130@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)

**Comment by penghaihui** [comment]
今天腾讯云工单新的回复：用户只要未登出，就能正常返回userid。userSig过期了，没有调用logout，其实还是未登出状态的。&nbsp;


所以如果不是主动退出，不能使用TIMManager.getInstance().getLoginUser()作为登录态判断
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiangJuHong/FlutterTencentImPlugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 晚上7:55
收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;;
抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66)





 
我将检查这个问题  如果是这个原因，我将进行修正.

**Comment by JiangJuHong** [comment]
原来是这个原因

**Comment by JarnTang** [comment]
> 今天腾讯云工单新的回复：用户只要未登出，就能正常返回userid。userSig过期了，没有调用logout，其实还是未登出状态的。&nbsp; 所以如果不是主动退出，不能使用TIMManager.getInstance().getLoginUser()作为登录态判断 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JiangJuHong/FlutterTencentImPlugin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月1日(星期六) 晚上7:55 收件人:&nbsp;"JiangJuHong/FlutterTencentImPlugin"<FlutterTencentImPlugin@noreply.github.com&gt;; 抄送:&nbsp;"No.1(海辉）"<313771130@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [JiangJuHong/FlutterTencentImPlugin] userSig过期重新登录问题 (#66) 我将检查这个问题 如果是这个原因，我将进行修正. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

那有建议使用哪个接口来判断是否登录呢？
