### ISSUE TITLE
[BUG] Android PlatformException parameter position is wrong 

### ISSUE THREAD

**Issue by shenjingfs** [JiangJuHong/FlutterTencentImPlugin#67]
**Describe the bug**
In version 0.2.35 (0.2.42 also), the PlatformException parameter position on the android platform is wrong: 
```
PlatformException(Sdk_Not_Login, 6014, null)
```

**Expected behavior**
```
PlatformException(6014, Sdk_Not_Login, null)
```

**Flutter version**
1.17.4

**Other**
This is where I found some errors, there may be other places
1. ValueCallBack.java line 46:
```
result.error(desc, String.valueOf(code), null);
```

2. CommonUtil.java line 28
``` 
result.error("Missing parameter", "Cannot find parameter `" + param + "` or `" + param + "` is null!", 5);
```

3. TencentImPlugin.java line 382 (I think need a custom error code):
``` 
result.error("login failed. ", "user is login", "user is already login ,you should login out first");
```

**Comment by JiangJuHong** [comment]
好的，我会修正它

**Comment by JiangJuHong** [comment]
它在 `0.2.43` 被修复!
