### ISSUE TITLE
针对单条消息设置离线推送

### ISSUE THREAD

**Issue by anlzy** [JiangJuHong/FlutterTencentImPlugin#68]
可以支持【针对单条消息设置离线推送】吗。现在有个需求，收到离线推送后，点击通知栏的通知，跳转到聊天页面。实现这个功能需要发消息时，在ext设置参数。
https://cloud.tencent.com/document/product/269/9234#.E9.92.88.E5.AF.B9.E5.8D.95.E6.9D.A1.E6.B6.88.E6.81.AF.E8.AE.BE.E7.BD.AE.E7.A6.BB.E7.BA.BF.E6.8E.A8.E9.80.81

**Comment by JiangJuHong** [comment]
我会查看文档，并确定是否会支持它

**Comment by JiangJuHong** [comment]
你好，由于该插件有升级到新版本计划，但是发现在最新版本中没有发现该接口(有可能是被废弃，也有可能是我们找到)，故暂时不提供支持计划.

**Comment by anlzy** [comment]
针对单条消息设置离线推送的内容。搜索【透传自定义内容】https://cloud.tencent.com/document/product/269/44516#.E9.80.8F.E4.BC.A0.E8.87.AA.E5.AE.9A.E4.B9.89.E5.86.85.E5.AE.B92

**Comment by JiangJuHong** [comment]
这是在发送消息前设置，所以我认为它应该归属在`发送消息`之中，在升级SDK期间，我将兼容并实现对应内容! 感谢您的反馈.

**Comment by JiangJuHong** [comment]
FlutterTencentIM插件已更新至 1.0.x，基于v5 SDK，优化参数、枚举等内容，如需要更新，请参考文档进行更新。注意：由于腾讯云 5.x api改动较大，请不要混用 5.x 和 4.x 接口，对应插件版本: 5.x -> 1.x ，4.x -> 0.x。项目地址：https://github.com/JiangJuHong/FlutterTencentImPlugin
