### ISSUE TITLE
升级0.2.x 版本以后的疑问

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#7]
你好作者，我的项目升级至0.2.x版本以后
dio的post请求 ，response 200状态的就会导致app闪退。但非200的和get 的response不受影响。

我回顾代码版本 升级0.2.x时，发现确实没有改变任何其他代码。仅仅是把im迁移至0.2.x。
也再次确认过，迁移到0.2.x之前 确实没有此问题
有没有可能是插件影响的呢?

**Comment by JiangJuHong** [comment]
你好，这是意料之中的现象，因为不是所有节点都经过处理，未处理的节点将导致闪退。不过不用担心，这个问题已经在修复中了，明天就将发布解决后的版本。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 峰硕 <notifications@github.com&gt;
发送时间: 2020年3月20日 19:39
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 升级0.2.x 版本以后的疑问 (#7)

**Comment by yuefeng007** [comment]
ok，感谢

**Comment by yuefeng007** [comment]
tencent_im_plugin: ^0.2.13  
图片消息和视频消息 闪退

**Comment by yuefeng007** [comment]
> tencent_im_plugin：^ 0.2.13
> android发送图片消息和视频消息

是我引入了 image_picker_saver插件的原因
