### ISSUE TITLE
使用插件报错

### ISSUE THREAD

**Issue by Hubertzzz** [JiangJuHong/FlutterTencentImPlugin#70]
注: /Users/hubertdou/.pub-cache/hosted/pub.flutter-io.cn/tencent_im_plugin-0.2.43/android/src/main/java/top/huic/tencent_im_plugin/TencentImPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/hubertdou/Documents/学蛤3.0/xuege/android/app/src/debug/AndroidManifest.xml:10:9-30 Error:
	Attribute application@label value=(xuege) from AndroidManifest.xml:10:9-30
	is also present at [com.tencent.imsdk:imsdk:4.6.1] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-46:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

要怎么解决

**Comment by JiangJuHong** [comment]
引用解决办法： https://github.com/MEnigma/flutter_rtmp/issues/8#issuecomment-638131795

**Comment by Hubertzzz** [comment]
解决了 十分感谢
