### ISSUE TITLE
发送视频消息时，对方收到的视频信息没有缩略图

### ISSUE THREAD

**Issue by penghaihui** [JiangJuHong/FlutterTencentImPlugin#71]
对方收到的视频信息为：
{nodeType: Video, videoSnapshotInfo: {width: 0, height: 0, path: }, videoInfo: {duration: 12, type: jpg, path: }}
如果发送端清除缓存后，从服务端下载的消息也一样没有缩略图，是不是缩略图上传服务器不成功。

**Comment by JiangJuHong** [comment]
请参考  #63

**Comment by penghaihui** [comment]
使用： TencentImPlugin.downloadVideoImage接口返回如下错误
下载图片失败:PlatformException(6021, Execution Error, uuid is empty)

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/89753545-51b28a80-db0b-11ea-8b71-67bf52605bcb.png)
请注意图片是否有效

**Comment by JiangJuHong** [comment]
` Execution Error, uuid is empty` 请注意 message 对象是否传递正确

**Comment by penghaihui** [comment]
应该没传错，跟TencentImPlugin.downloadVideo这个接口传的MessageEntity message参数是一样的，而TencentImPlugin.downloadVideo这个接口没问题，能返回视频，而且能播放；

MessageEntity message转为json是这样的{customInt: 0, read: true, self: true, id: 2300898618, uniqueId: 6859177196236631354, customStr: , timestamp: 1597026641, peerReaded: false, sender: 10, sessionId: 9, sessionType: C2C, userInfo: {birthday: 0, identifier: 10, role: 0, gender: 0, level: 0, nickName: 彭大大, language: 0, customInfo: {}, selfSignature: , allowType: AllowType_Type_AllowAny, faceUrl: https://ccds-1253577682.cos.ap-guangzhou.myqcloud.com/common/1586768658436.jpg, location: , customInfoUint: {}}, status: SendSucc, rand: 2300898618, seq: 35109, note: [视频]}
I/flutter (27755): MSG2:{nodeType: Video, videoSnapshotInfo: {width: 0, height: 0, path: }, videoInfo: {duration: 8, type: jpg, path: }}

VideoMessageNode videoNode 转成json :
{nodeType: Video, videoSnapshotInfo: {width: 0, height: 0, path: }, videoInfo: {duration: 8, type: jpg, path: }}
里面没有uuid的

**Comment by JiangJuHong** [comment]
UUID 为后台获得，message 中必须包含 `sessionId、sessionType、rand、seq` 参数，请提供你的设备信息、环境信息、错误日志、以及复现率
