### ISSUE TITLE
视频下载缩略图失败，uuid一直为空

### ISSUE THREAD

**Issue by JiangJuHong** [JiangJuHong/FlutterTencentImPlugin#74]
视频下载缩略图失败，uuid一直为空.

**Comment by JiangJuHong** [comment]
目前正在等待腾讯云工单回复

**Comment by JiangJuHong** [comment]
经过排查，造成原因是 demo 中使用了 webp 格式作为缩略图，而im SDK 不支持webp格式作为缩略图，demo 已经缩略图格式更改为 jpeg，请使用时注意.

**Comment by JiangJuHong** [comment]
@abner-hello-world @songjiabin @penghaihui 解决办法如上

**Comment by songjiabin** [comment]
谢谢

**Comment by abner-hello-world** [comment]
> @abner-hello-world @songjiabin @penghaihui 解决办法如上
谢谢
