### ISSUE TITLE
视频缩略图不能下载，还有就是ios视频可以下载无法播放，Android可以，您的demo ios视频也不能播放

### ISSUE THREAD

**Issue by abner-hello-world** [JiangJuHong/FlutterTencentImPlugin#75]
谢谢大佬的插件

**Comment by JiangJuHong** [comment]
1. 视频缩略图不能下载：          参考 #74 
2. ios视频可以下载无法播放：  是否运行过程中使用的模拟器，请尝试使用真机设备

**Comment by JiangJuHong** [comment]
经过测试，当使用 `video_player` 插件时，无法在 ios 模拟器播放视频

**Comment by JiangJuHong** [comment]
如果没有其它疑问，该问题将会被关闭  视频缩略图不能下载的问题，将移交到 #74
