### ISSUE TITLE
对方发一条消息会收到3次新消息的回调

### ISSUE THREAD

**Issue by AcYangle** [JiangJuHong/FlutterTencentImPlugin#76]
![image](https://user-images.githubusercontent.com/15205440/90235547-16d68c80-de54-11ea-97da-7f1f996dc4fc.png)
集成demo中的im.dart，对方发消息时，会收到三次新消息的回调，然后会出现3条相同消息

**Comment by AcYangle** [comment]
![image](https://user-images.githubusercontent.com/15205440/90235922-a4b27780-de54-11ea-81ef-57f66506f6bc.png)
另外params回调的是List，add到data不显示消息
于是我改成了这样
![image](https://user-images.githubusercontent.com/15205440/90236140-f22ee480-de54-11ea-8dcd-bc6fd1003dbe.png)
便出现了上述问题

请求作者协助一下

**Comment by JiangJuHong** [comment]
参考 #45
