### ISSUE TITLE
获取好友列表，返回40002，

### ISSUE THREAD

**Issue by kazeik** [JiangJuHong/FlutterTencentImPlugin#77]
在登录成功后，拉取自己的登录信息成功后，
去获取好友列表，返回40002（请求参数错误，没有指定需要拉取资料的用户帐号。）
 Unhandled Exception: PlatformException(40002, Err_Profile_To_Account_Empty, Err_Profile_To_Account_Empty)。

**Comment by JiangJuHong** [comment]
请确保是否拥有好友，在我的曾经几次测试中，没有好友时拉取好友列表将会返回错误码，这应该是腾讯云SDK做的特殊处理.
