### ISSUE TITLE
在puv上面拉插件到项目上会报错

### ISSUE THREAD

**Issue by hackerjmss** [JiangJuHong/FlutterTencentImPlugin#78]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
D:\jdim\android\app\src\debug\AndroidManifest.xml:10:9-29 Error:
	Attribute application@label value=(jdim) from AndroidManifest.xml:10:9-29
	is also present at [com.tencent.imsdk:imsdk:4.6.1] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-46:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by hackerjmss** [comment]
增加了tools以后 又报错了很多问题，不知道什么问题 直接用不了

**Comment by JiangJuHong** [comment]
参考 #70

**Comment by hackerjmss** [comment]
我按方法操作以后，会报下方这个错误

Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 3; Ԫ������ "application" ������ƥ��Ľ������ "</application>" ��ֹ��

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by JiangJuHong** [comment]
请尝试使用 flutter clean，如果依旧出现错误可以尝试使用 Android Studio 进行 build

**Comment by hackerjmss** [comment]
可以了。谢谢老大
