### ISSUE TITLE
我想监听自定义消息，但监听到自定义消息note里的内容是 “[其它消息]”，是我方式不对吗

### ISSUE THREAD

**Issue by 965390267** [JiangJuHong/FlutterTencentImPlugin#79]

**Comment by JiangJuHong** [comment]
note 为消息类型的描述信息，由内部封装，如果你需要对 CustomMessage  进行不同的显示，可根据 elem 属性进行判断.

**Comment by 965390267** [comment]
我是用这个监听另外一个设备发送过来的自定义消息 TencentImPlugin.addListener(_messageListener);，但是解析param参数发现里边没有我发的自定义消息，是我用的方式不对吗

**Comment by JiangJuHong** [comment]
监听器原型为:
````
 _messageListener(ListenerTypeEnum type, params) {
  // you code
};
````

你需要判断 type == ListenerTypeEnum.NewMessage 时，params则为 MessageEntity 对象

**Comment by 965390267** [comment]
messageListener(ListenerTypeEnum type, params) {
    // you code
    if (type == ListenerTypeEnum.NewMessages) {
      dynamic obj = jsonEncode(params);
      print(obj);
    }
  }
我这自定义消息打印的 就是下边的数据，没看到我发送过来的字段，是不是不能直接打印出来嘛
日志拦截: ListenerTypeEnum.NewMessages

I/flutter ( 5011): 日志拦截: [{"customInt":0,"read":false,"self":true,"id":"65965603","uniqueId":6862278890533850659,"customStr":"","timestamp":1597748811,"peerReaded":false,"sender":"DEV_TUTOR_45","sessionId":"DEV_TUTOR_45","sessionType":"C2C","userInfo":{"birthday":0,"identifier":"DEV_TUTOR_45","role":0,"gender":0,"level":0,"nickName":"RHY","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"http://store.91yunshi.com/storage/guagua/1920*1080*ee6a939be9f2260d0a86b5f8c790f1ac.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":65965603,"seq":1634370022,"note":"[其它消息]"}]

**Comment by JiangJuHong** [comment]
请使用 debug 调试，节点数据存储在 `elemList` 属性当中

**Comment by 965390267** [comment]
请问一下自定义的消息都是在data里自己定义数据格式吗，我的web端除了data还有description和extension字段，网页上3个字段都用着的，这是安卓和和web的区别吗

**Comment by JiangJuHong** [comment]
腾讯云 SDK 在某一版本已经将 desc 和 exten 字段标记为废弃，所以本质上我也直接取消了字段，建议直接使用 data

**Comment by 965390267** [comment]
好的，谢谢大佬耐心解答(*￣︶￣)
