### ISSUE TITLE
什么时候能到正式版？

### ISSUE THREAD

**Issue by iyuhang** [JiangJuHong/FlutterTencentImPlugin#8]
什么时候能到正式版？

**Comment by JiangJuHong** [comment]
这个版本几乎已经稳定，我已经在正式项目中使用。如果不出意外，它将在四月发布。







------------------ 原始邮件 ------------------
发件人: Ansen <notifications@github.com&gt;
发送时间: 2020年4月1日 21:42
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 什么时候能到正式版？ (#8)





 
什么时候能到正式版？

**Comment by iyuhang** [comment]
我看了一下您的接口文档
下面这几个不知实现了没有，或者实现计划
1. 未读数的处理
2. 离线通知的处理 （这个有计划什么时候吗）
3. 下载原图（看到有下载缩略图）
4. 离线漫游消息

**Comment by JiangJuHong** [comment]
现除了离线推送没有，其它的功能都具备。离线推送是在计划中，但是我不确定它是否能在四月完成。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ansen <notifications@github.com&gt;
发送时间: 2020年4月1日 22:21
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: 蒋具宏 <690717394@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 什么时候能到正式版？ (#8)





 
我看了一下您的接口文档
 下面这几个不知实现了没有，或者实现计划
  
未读数的处理 

离线通知的处理 （这个有计划什么时候吗） 

下载原图（看到有下载缩略图） 

离线漫游消息
