### ISSUE TITLE
IOS端  调用downloadVideoImage  downloadSound 报错    安卓能下载成功

### ISSUE THREAD

**Issue by MrshawY** [JiangJuHong/FlutterTencentImPlugin#80]
![lALPDiQ3MEr2hZzNApzNBtY_1750_668 png_720x720q90g](https://user-images.githubusercontent.com/46661487/90515783-b5852500-e195-11ea-86b8-f3b065ac40d3.jpg)

**Comment by JiangJuHong** [comment]
请将您的应用版本升级到最新，如果依旧出现该问题，请提供更加详细的信息.

**Comment by MrshawY** [comment]
依然还是报错   请问具体应该提供哪些信息给您呢   sessionId、sessionType、razhhend、seq 这些属性都会有

**Comment by JiangJuHong** [comment]
如果Android能够下载成功，理论上来说ios也会成功，我没有在腾讯云 im 的错误码中找到-1004

**Comment by JiangJuHong** [comment]
请确认IOS是否赋予访问文件库的权限
