### ISSUE TITLE
在测试过程中，im返回了大量的信息，怎样查看他的当前返回内容？

### ISSUE THREAD

**Issue by hackerjmss** [JiangJuHong/FlutterTencentImPlugin#81]
/imsdk   (28093): TIM: 2020-08-18 13:48:50.597/I/28093-28183   /Cache     -cache_manager.cpp.33  Init                                 /start init current identifier: identifier:15327707918 path:/data/user/0/com.example.jdim/files
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.597/I/28093-28183   /Cache     -cache_manager.cpp.96  Uninit                               /cache is not inited
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.597/I/28093-28183   /Cache     -sqlite_store.cpp.1070  Open                                /Start Open Sqlite DB path:/data/user/0/com.example.jdim/files identifier:15327707918
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.602/I/28093-28183   /Cache     -sqlite_store.cpp.1176  Open                                /End Open Sqlite DB path:/data/user/0/com.example.jdim/files
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.602/I/28093-28183   /Cache     -cache_manager.cpp.179  GetDB                               /Thread DB -1183931936 Open DB path:/data/user/0/com.example.jdim/files identifier:15327707918
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.602/I/28093-28183   /Cache     -imcore_cache.cpp.448  Init                                 /init conv cache finish|size:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.602/I/28093-28183   /Msg       -imcore_message_util.cpp.212  InsertKeys                    /insert key size: 0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.683  Init                                 /init id cache
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.699  Init                                 /init id cache finish|size:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.807  Init                                 /init friendship profile cache
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.825  Init                                 /init friendship profile cache finish|size:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.1029  Init                                /init group ship cache
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.1045  Init                                /init group detail cache finish|size:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /Cache     -imcore_cache.cpp.1050  Init                                /init group base cache finish|size:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.603/I/28093-28183   /IMSDK     -BaseManager.0                                              /initStorage succ
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.654/I/28093-28093   /IMSDK     -TIMManager.0                                               /login : userID = 15327707918
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.654/I/28093-28093   /Common    -imcore_manager.cpp.492  MakeLoginDicision                  /fromStatus:0|toStatus:1|param.identifier_:15327707918
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.655/I/28093-28093   /Common    -imcore_manager.cpp.552  LoginInternal                      /Login
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.665/I/28093-28093   /Common    -transport.cpp.300  Pack                                    /pack without backsig
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.666/I/28093-28183   /Network   -imsession_monitor.cpp.284  Record                          /record|content:date_time=1597758530&sdk_app_id=1400412952&conn_succ=1&conn_time=151&conn_last=1417870&sdk_client_ip=171.43.7.236&sso_ip=113.96.237.62&sso_port=8080&conn_reason=0&send_count=21&send_succ_count=21&send_high_count=8&send_high_succ_count=7&avg_rtt=53&net_type=wifi&state=1&timestamp=2020-08-18T13:48:50.666+0800&sso_ip_src=4&sso_ip_list=113.96.237.62:8080,59.36.121.50:8080,59.36.121.65:8080,183.3.225.54:8080&failed_ip_list=&error_code=0&reg_error_code=0&error_msg=
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.669/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:wtlogin64.trans_emp|seq:3048315539|prior:true|timeout:10000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.669/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315539|status:2|size:498|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.671/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315539|status:4|size:498|sent:498
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.745/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:wtlogin64.trans_emp|seq:3048315539|code:0|size:366|totalsize:366
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315539|status:6|size:498|sent:498
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Common    -transport.cpp.394  Unpack                                  /decrypt pkg succ
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Common    -transport.cpp.411  Unpack                                  /reply 0, get data succ:254
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Common    -tls.cpp.272  Unpack0xa0b                                   /0xa0b unpack succ
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Common    -tls.cpp.323  operator()                                    /ret : 0, rsp: (
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Common    -imcore_manager.cpp.653  operator()                         /sdkAppId: 1400412952, identifier: 15327707918, tinyid: 144115224022280906
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Network   -imsession_sso_session.cpp.569  UpdateUser                  /reged_: false, auth from identifier: , tinyid: 0 to identifier: 15327707918, tinyid: 144115224022280906
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.746/I/28093-28183   /Network   -imsession_session_config.cpp.470  operator()               /Write config, sdkAppId: 1400412952, identifier: 15327707918, tinyid: 144115224022280906
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.747/I/28093-28183   /Msg       -session_task.cpp.124  Encode                               /reg |encode|cmd:im_open_status.stat_reg|buf:08011000180b2000280030003a2463306562306537622d323464392d343338612d393239322d616163636662646135353731a001cad5cbf48581808002b001d20fba0100
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.748/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:im_open_status.stat_reg|seq:3048315540|prior:true|timeout:5000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.749/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315540|status:2|size:380|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.750/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315540|status:4|size:380|sent:380
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.785/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:im_open_status.stat_reg|seq:3048315540|code:0|size:136|totalsize:136
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.785/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315540|status:6|size:380|sent:380
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Msg       -session_task.cpp.131  Decode                               /reg|decode|code:0|desc:|cmd:im_open_status.stat_reg|buf:0a02080018c2b8eff90520002800320c3137312e34332e372e3233363881354078
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Network   -imsession_monitor.cpp.284  Record                          /record|content:date_time=1597758530&sdk_app_id=1400412952&conn_succ=1&conn_time=151&conn_last=1417989&sdk_client_ip=171.43.7.236&sso_ip=113.96.237.62&sso_port=8080&conn_reason=0&send_count=21&send_succ_count=21&send_high_count=9&send_high_succ_count=9&avg_rtt=51&net_type=wifi&state=1&timestamp=2020-08-18T13:48:50.786+0800&sso_ip_src=4&sso_ip_list=113.96.237.62:8080,59.36.121.50:8080,59.36.121.65:8080,183.3.225.54:8080&failed_ip_list=&error_code=0&reg_error_code=0&error_msg=
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Network   -imsession_sso_session.cpp.1319  operator()                 /reg success|clien ip: 171.43.7.236, port: 6785, hello interval: 120000, serverTimeDiff: 0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Network   -imsession_sso_session.cpp.1437  EnableHeartbeat            /enable heartbeat, interval: 120000
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Network   -looper_impl.cpp.531  EmplacePeroidTask                     /looper stat|name:looper_logic|EmplacePeroidTask, task id = 10, now time = 2561931, fire time = 2681931
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Cache     -cache_manager.cpp.33  Init                                 /start init current identifier:15327707918 identifier:15327707918 path:/data/user/0/com.example.jdim/files
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.786/I/28093-28183   /Cache     -cache_manager.cpp.36  Init                                 /has inited and same identifier
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.787/I/28093-28183   /Common    -imcore_manager.cpp.567  operator()                         /code: 0, errMsg:
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.787/I/28093-28183   /IMSDK     -BaseManager.0                                              /Login succ, user: 1400412952:1400412952:15327707918:1400412952
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Network   -imsession_session_config.cpp.470  operator()               /Write config, sdkAppId: 1400412952, identifier: 15327707918, tinyid: 144115224022280906
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Cache     -imcore_cache.cpp.426  GetSyncC2CCookie                     /get syncC2CCookie|cookie:10b1b5eff9052889bebf8a0f38b183a4b907
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.4302  Encode                  /get openbdh addr
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.4346  Encode                  /get openbdh addr|encode|cmd:IMBDH.GetKeyAndIp|buf:0a123134343131353232343032323238303930361a5208231098b6e29b051a48f62ae601d40a25b8a9329f952ea99be5662809ce7d2fce36e9afb6ab121b0fcaac2ee2f1810838f2d63d0cd936b25dc210871b7a151b429399997092d482c45b141a90ca8e16623d20032a0301020430e5fd8a8002
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2332  Encode                  /msg sync|param|online:false|flag:0|cookie:10b1b5eff9052889bebf8a0f38b183a4b907
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2379  Encode                  /msg sync|encode|cmd:im_open_msg.msg_sync|buf:0a1210b1b5eff9052889bebf8a0f38b183a4b9071000200028014001
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.1672  Encode                  /get conversations|param|identifier:15327707918
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.789/I/28093-28183   /Msg       -imcore_conversation_task.cpp.1708  Encode                  /get conversations|encode|cmd:Recentcontact.PageGet_PB|buf:08cad5cbf4858180800210001801
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.790/I/28093-28183   /Group     -imcore_group_task.cpp.1990  Encode                         /get joined groups|param|onlySeq:1|count:100|offset:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.790/I/28093-28183   /Group     -imcore_group_task.cpp.2072  Encode                         /get joined groups|encode|cmd:group_open_tcp_svc.get_group_list|buf:080112160a100a0028013801a2010418002001a8010110641800
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.793/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:IMBDH.GetKeyAndIp|seq:3048315541|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.793/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315541|status:2|size:420|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.796/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:imopenstat.report|seq:3048315542|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.796/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315542|status:2|size:668|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.799/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:im_open_msg.msg_sync|seq:3048315543|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.799/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315543|status:2|size:332|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.801/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:Recentcontact.PageGet_PB|seq:3048315544|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.801/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315544|status:2|size:324|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.804/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:group_open_tcp_svc.get_group_list|seq:3048315545|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.804/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315545|status:2|size:348|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.806/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315541|status:4|size:420|sent:420
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.807/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315542|status:4|size:668|sent:668
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.807/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315543|status:4|size:332|sent:332
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.807/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315544|status:4|size:324|sent:324
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.808/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315545|status:4|size:348|sent:348
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.840/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:imopenstat.report|seq:3048315542|code:0|size:96|totalsize:96
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.840/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315542|status:6|size:668|sent:668
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.840/I/28093-28183   /Common    -data_report.cpp.205  operator()                            /report imcore data succ
W/AudioTrack(28093): Spurious audio timestamp (frame position mismatch): 59322186, 2562015144, 2562037642, 1409585666, 67671040, 67670962
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:group_open_tcp_svc.get_group_list|seq:3048315545|code:0|size:912|totalsize:128
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315545|status:6|size:348|sent:348
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Group     -imcore_group_task.cpp.1886  Decode                         /get joined groups|decode|code:0|desc:|buf:0a06080012026f6b10011a021000
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Group     -imcore_group_task.cpp.1980  Decode                         /get group members|decode|code:0|desc:ok
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:im_open_msg.msg_sync|seq:3048315543|code:0|size:784|totalsize:128
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.902/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315543|status:6|size:332|sent:332
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2385  Decode                  /msg sync|decode|code:0|desc:|isFinish:false|buf:0a020800121210c3b8eff9052889bebbfa0f38c8b980bb07180228c3b8eff9053000
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:IMBDH.GetKeyAndIp|seq:3048315541|code:0|size:656|totalsize:536
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315541|status:6|size:420|sent:420
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.4353  Decode                  /get openbdh addr|decode|code:0|desc:|buf:0a38084f53e0434964ae58216962ca31c1e439013fe523da58a8dc13db53f1d82c263092947ffb81ba1896d0cde5016df0aeb7a13a05737544d412104232434253387363507a6d57487a58761a87010804120b0801150e12b1e81880a001120b0801150e7489581880a001120b08011565591bf31880a001120b080115655b3e661880a001224f080112453043020101043c303a02010102010102045e92eaca02037a1db90204e8b1120e02045889740e02037a1afd0204f31b59650204663e5b6502045f43c543020424cc4ccd040018c38a8ffa051a4e0802120b080115b703e9e81880a001120b0801150e12af2e1880a001120b0801157160d0171880a001120b080115249ef2221880a001120b0801159dfff3e21880a0011a09702e717069632e636e1a4e0803120b080115b703e9e81880a001120b0801150e12af2e1880a001120b0801157160d0171880a001120b080115249ef2221880a001120b0801159dfff3e21880a0011a09702e717069632e636e1a450801120b0801153b24712a189fa002120b0801153b24712a189fa002120b0801157b974f68189fa002120b0801157b974f68189fa0021a0d7
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.4412  Decode                  /get openbdh addr|decode|code:0|desc:
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:Recentcontact.PageGet_PB|seq:3048315544|code:0|size:120|totalsize:120
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315544|status:6|size:324|sent:324
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.1715  Decode                  /get conversations|decode|code:0|desc:|buf:10001801c23e024f4bc83e00d23e00da3e00
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.1787  Decode                  /get conversations complete
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2332  Encode                  /msg sync|param|online:false|flag:2|cookie:10c3b8eff9052889bebbfa0f38c8b980bb07
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2379  Encode                  /msg sync|encode|cmd:im_open_msg.msg_sync|buf:0a1210c3b8eff9052889bebbfa0f38c8b980bb071002200028014001
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.903/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2073  operator()              /get conversations|decode|code:0|desc:
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.911/I/28093-28183   /Network   -imsession_sso_session.cpp.742  SendRawData                 /send pkg|cmd:im_open_msg.msg_sync|seq:3048315546|prior:false|timeout:30000|channelid:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.911/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315546|status:2|size:332|sent:0
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.912/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315546|status:4|size:332|sent:332
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.950/I/28093-28183   /Network   -imsession_sso_session.cpp.1027  OnPacketDecode             /recv pkg|cmd:im_open_msg.msg_sync|seq:3048315546|code:0|size:104|totalsize:104
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.951/I/28093-28183   /Network   -channel.cpp.121  OnPacketStatus                            /packet status|id:0|seq:3048315546|status:6|size:332|sent:332
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.951/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2385  Decode                  /msg sync|decode|code:0|desc:|isFinish:true|buf:0a020800
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.952/I/28093-28183   /Cache     -imcore_cache.cpp.389  UpdateSyncC2CCookie                  /update syncC2CCookie|cookie:10c3b8eff9052889bebbfa0f38c8b980bb07
I/imsdk   (28093): TIM: 2020-08-18 13:48:50.961/I/28093-28183   /Msg       -imcore_conversation_task.cpp.2394  Decode                  /msg sync|decode|end, map_msgs_ size is zero

如上图所示，我想请问一下，怎么样查看登录的回调内容？

**Comment by JiangJuHong** [comment]
不是很明白你想表达的意思

**Comment by hackerjmss** [comment]
在我调用它的登录接口成功登录后，在控制台里面会返回大量关于TIM的内容，我找不到只返回登录错误，或者登录成功的内容。

**Comment by hackerjmss** [comment]
请问一下 我看到有demo的。能发一下这个demo 的git地址吗

**Comment by JiangJuHong** [comment]
登陆成功后不确定控制台会不会打印，这些打印的大部分均为腾讯云内部打印

**Comment by JiangJuHong** [comment]
克隆此项目 example 目录就是demo

**Comment by hackerjmss** [comment]
那如果登录失败，我应该怎么获取他的code，以及错误提示呢？

**Comment by JiangJuHong** [comment]
这为Dart语法部分，其中正确的返回结果以及错误的返回结果都通过 Future 进行操作

**Comment by hackerjmss** [comment]
可以帮我写个例子吗。跪求

**Comment by JiangJuHong** [comment]
请参考demo
