### ISSUE TITLE
你好，我把appId和userSig换成自己的后创建群报错，具体错误如下

### ISSUE THREAD

**Issue by YunhuiLiu140502** [JiangJuHong/FlutterTencentImPlugin#82]
Unhandled Exception: PlatformException(10004, all defined key is invalid, all defined key is invalid)
![image](https://user-images.githubusercontent.com/22772242/91287326-2cd43d80-e7c2-11ea-8243-c903e96cf28f.png)
![image](https://user-images.githubusercontent.com/22772242/91287357-3b225980-e7c2-11ea-9fb3-4eb704015436.png)
![image](https://user-images.githubusercontent.com/22772242/91287382-41b0d100-e7c2-11ea-8572-49bfc3ca19e7.png)

**Comment by JiangJuHong** [comment]
创建群聊时条件比较苛刻，存在参数验证，比如私有群创建时必须设置某某某参数，具体是什么我有点忘记了，可以参考：https://cloud.tencent.com/document/product/269/1502#.E7.BE.A4.E7.BB.84.E5.BD.A2.E6.80.81.E4.BB.8B.E7.BB.8D

**Comment by JiangJuHong** [comment]
Demo中常见群组存在不足，在UI界面上`未完全展示或展示过多`，所以很容易引发 10004，如果你集成到你的项目中，按照业务逻辑，创建就很简单了

**Comment by JiangJuHong** [comment]
后期如果有机会，我将重构Demo，当然，是在升级腾讯云IM版本过后。

**Comment by YunhuiLiu140502** [comment]
使用你的demo是可以创建群的，appId和userSig换成自己的就不行，创建群参数是一样的，除了这两个地方还有需要修改的地方吗

**Comment by JiangJuHong** [comment]
如果是这样的话就应该是权限问题了，你可以在腾讯云后台设置群组的权限
