### ISSUE TITLE
请问下有群成员禁言和踢出接口吗

### ISSUE THREAD

**Issue by 965390267** [JiangJuHong/FlutterTencentImPlugin#84]

**Comment by JiangJuHong** [comment]
禁言请参考：modifyMemberInfo 接口
踢人请参考：deleteGroupMember 接口

**Comment by 965390267** [comment]
请教下我想跳到被@的消息列有没有什么实现方法，我现在是后台记录@消息，另一端取到@的消息然后清空消息拉取一定条数，但是这样就没法滚到最新的消息

**Comment by JiangJuHong** [comment]
抱歉，暂未研究该内容，不过理论上来说，知道消息内容，就可以知道消息内容在 ListView 渲染的位置，知道位置，就自然能跳转。

**Comment by 965390267** [comment]
好的，谢谢你。我们需求是被@的历史消息也要跳，但也不能把所有消息都拉下拉。

**Comment by 965390267** [comment]
我看getMessages这个接口是只能从上拉取之前的历史消息，有没有什么方法可以往后拉消息列表呢

**Comment by JiangJuHong** [comment]
如果你想要实现这个，可以拉取历史记录后选择缓存到你自定义的List集合中

**Comment by 965390267** [comment]
好的，Thanks♪(･ω･)ﾉ
