### ISSUE TITLE
使用demo发送视频的时候，会报错

### ISSUE THREAD

**Issue by hackerjmss** [JiangJuHong/FlutterTencentImPlugin#85]
W/libEGL  (13863): EGLNativeWindowType 0x713b9a1010 disconnect failed
D/ThumbnailPlugin(13863): buildThumbnailFile( format:0, maxh:0, maxw:0, timeMs:0, quality:25 )
D/ThumbnailPlugin(13863): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:0, quality:25 )
D/ThumbnailPlugin(13863): buildThumbnailFile( written:9397 )
I/ExoPlayerImpl(13863): Init dcf0c95 [ExoPlayerLib/2.9.6] [PD1806, vivo NEX A, vivo, 29]
E/ExoPlayerImplInternal(13863): Source error.
E/ExoPlayerImplInternal(13863): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(13863): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
E/ExoPlayerImplInternal(13863): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
E/ExoPlayerImplInternal(13863): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(13863): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(13863): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(13863): 	at java.lang.Thread.run(Thread.java:919)
E/flutter (13863): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream., null)
E/flutter (13863):

一直在处理中，然后报这个错

**Comment by JiangJuHong** [comment]
请检查视频是否正确，或更换视频格式后重试

**Comment by hackerjmss** [comment]
视频是正常的mp4格式的

**Comment by JiangJuHong** [comment]
````
D/ThumbnailPlugin(13863): buildThumbnailFile( format:0, maxh:0, maxw:0, timeMs:0, quality:25 )
D/ThumbnailPlugin(13863): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:0, quality:25 )
D/ThumbnailPlugin(13863): buildThumbnailFile( written:9397 )
````
或许这不是腾讯云IM的问题，而是无法生成视频缩略图，请仔细检查您的代码

**Comment by hackerjmss** [comment]
代码应该没错，是完全按demo来的 没有更改

**Comment by hackerjmss** [comment]
并且也获取到了缩略图

**Comment by JiangJuHong** [comment]
````
E/flutter (13863): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream., null)
````
请关注这一行信息，代表所有的视频解析器均无法解析你的视频流信息.

**Comment by JiangJuHong** [comment]
请尝试更换视频格式。

**Comment by hackerjmss** [comment]
在demo中，如果选用相册，上传视频文件 会解析后缀为jpg格式
如果使用选择录像，拍出来的视频再上传 就会解析成mp4

**Comment by JiangJuHong** [comment]
可能是demo中选用的图片选取插件有问题，后期集成新版IMSDK后会同步更新Demo

**Comment by hackerjmss** [comment]
多久会出来

**Comment by JiangJuHong** [comment]
暂无准确时间

**Comment by JiangJuHong** [comment]
请将插件集成到您的系统中的时候进行相应更改，Demo仅为示例

**Comment by hackerjmss** [comment]
经过测试，同一个视频文件 他只是偶尔性的出这个问题。

**Comment by JiangJuHong** [comment]
目前暂未遇到该问题，如果有更准确的复现手段，我将会优先排查。

**Comment by hackerjmss** [comment]
还有个问题，就是在聊天界面中，对方发送消息，不会实时显示，切换出来才会看到未读，

**Comment by JiangJuHong** [comment]
这是Demo的问题，Demo并不完善，只是一个功能的展示，请在实际使用中根据自己的业务逻辑进行更改
