### ISSUE TITLE
getMessage 返回一直为空

### ISSUE THREAD

**Issue by TEENSTITAN** [JiangJuHong/FlutterTencentImPlugin#86]
/// 获取消息
    TencentImPlugin.getMessages(
      sessionId: widget.id,
      sessionType: SessionType.Group,
      number: 20,
    ).then((res) {
      print("getMessages-->" + res.length.toString());
    });

**Comment by JiangJuHong** [comment]
请注意会话中是否有消息，可以尝试创建一个新会话
