### ISSUE TITLE
您好，在创建群组成功后，会话列表会出现一个System会话，并且发送过来的数据是空的

### ISSUE THREAD

**Issue by hackerjmss** [JiangJuHong/FlutterTencentImPlugin#87]

**Comment by hackerjmss** [comment]
群提示节点,未解析制定规则

**Comment by TEENSTITAN** [comment]
getMessages() 能获取到本 GroupId 的消息列表吗？

**Comment by hackerjmss** [comment]
可以获取

**Comment by JiangJuHong** [comment]
能否发出完整的数据格式，又便于排查问题

**Comment by hackerjmss** [comment]
I/flutter (14030): [{"customInt":0,"read":true,"self":false,"id":"1760178797","uniqueId":6055146093,"customStr":"","timestamp":1598942659,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"https://baike-med-1256891581.file.myqcloud.com/yidian/production/common/image/common_logo.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":1760178797,"seq":1,"note":"[群提示消息]"},{"customInt":0,"read":true,"self":false,"id":"616585683","uniqueId":9206520275,"customStr":"","timestamp":1598942695,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny

**Comment by JiangJuHong** [comment]
数据不完整，请提供完整数据。注意：请不要使用 print 打印，请使用Debug模式进行获取变量值

**Comment by hackerjmss** [comment]
[{"customInt":0,"read":true,"self":false,"id":"1760178797","uniqueId":6055146093,"customStr":"","timestamp":1598942659,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"https://baike-med-1256891581.file.myqcloud.com/yidian/production/common/image/common_logo.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":1760178797,"seq":1,"note":"[群提示消息]"},{"customInt":0,"read":true,"self":false,"id":"616585683","uniqueId":9206520275,"customStr":"","timestamp":1598942695,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"https://baike-med-1256891581.file.myqcloud.com/yidian/production/common/image/common_logo.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":616585683,"seq":2,"note":"[群提示消息]"},{"customInt":0,"read":true,"self":false,"id":"962917488","uniqueId":13847819376,"customStr":"","timestamp":1598944619,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"https://baike-med-1256891581.file.myqcloud.com/yidian/production/common/image/common_logo.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":962917488,"seq":3,"note":"[群提示消息]"},{"customInt":0,"read":true,"self":false,"id":"832029568","uniqueId":18011898752,"customStr":"","timestamp":1598946676,"peerReaded":false,"sender":"@TIM#SYSTEM","sessionId":"@TGS#2RAPAVVGX","sessionType":"Group","userInfo":{"birthday":0,"identifier":"@TIM#SYSTEM","role":0,"gender":0,"level":0,"nickName":"系统消息","language":0,"customInfo":{},"selfSignature":"","allowType":"AllowType_Type_AllowAny","faceUrl":"https://baike-med-1256891581.file.myqcloud.com/yidian/production/common/image/common_logo.png","location":"","customInfoUint":{}},"status":"SendSucc","rand":832029568,"seq":4,"note":"[群提示消息]"}]

**Comment by JiangJuHong** [comment]
抱歉，我忘了 elemList 不会序列化到json了，我可以看下Debug的elemList的值么

**Comment by hackerjmss** [comment]
![image](https://user-images.githubusercontent.com/69739901/91830038-c98c5480-ec74-11ea-853a-9dea1968a9cf.png)

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/91830113-e9bc1380-ec74-11ea-87c8-8353eddb1ad3.png)
麻烦把 elemList 展开一下

**Comment by hackerjmss** [comment]
![image](https://user-images.githubusercontent.com/69739901/91830211-153efe00-ec75-11ea-8216-2c18bff3ac50.png)

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/91830694-b2019b80-ec75-11ea-90a8-55f7a5436b04.png)
这些内容就是数据

**Comment by JiangJuHong** [comment]
tipsType 对应内容为: 
![image](https://user-images.githubusercontent.com/17740963/91830770-c80f5c00-ec75-11ea-8532-b6bcd5b2c4d4.png)

**Comment by hackerjmss** [comment]
好的 感谢耐心的教导！
