### ISSUE TITLE
创建了群组，会话里面多了一个系统会话、返回没有数据

### ISSUE THREAD

**Issue by hackerjmss** [JiangJuHong/FlutterTencentImPlugin#88]
特别不好意思，刚刚解决的是群组里面自己返回的内容。
现在会出现一个系统会话。
![1598956777](https://user-images.githubusercontent.com/69739901/91840016-95b82b80-ec82-11ea-87cf-da3c6275367e.png)

**Comment by hackerjmss** [comment]
或者说，怎样不拉取系统会话？

**Comment by JiangJuHong** [comment]
系统会话是系统内部会话，貌似很多消息都没节点，可以通过   sessionType != SessionType.System 进行渲染的时候过滤，但是没法在拉取的时候过滤
