### ISSUE TITLE
直播环境中创建 AVChatRoom 类型的群组，发送消息成功，但是无法获取到消息，listener 也没调用？

### ISSUE THREAD

**Issue by TEENSTITAN** [JiangJuHong/FlutterTencentImPlugin#89]
**日志信息如下**

群组信息：
`getGroupInfo-->{groupType: AVChatRoom, maxMemberNum: 1000, groupOwner: 000001, custom: {}, groupId: 2_1598954101170, resultCode: 0, groupNotification: , memberNum: 2, resultInfo: , faceUrl: , groupName: 2_1598954101170, addOption: TIM_GROUP_ADD_ANY, createTime: 1598954101, groupIntroduction: , silenceAll: false, lastMsgTime: 0, onlineMemberNum: 0, lastInfoTime: 1599012845}`

发送一条消息：
`sendMessage-->{customInt: 0, read: true, self: true, id: 1912880557, uniqueId: 220956212653, customStr: , timestamp: 1599013203, peerReaded: false, sender: 000001, sessionId: 2_1598954101170, sessionType: Group, userInfo: {birthday: 0, identifier: 000001, role: 0, gender: -793067059891194693, level: 0, nickName: 李小龙, language: 0, customInfo: {}, selfSignature: , allowType: AllowType_Type_AllowAny, faceUrl: https://aliyuncs.com/950b0c8d-803e-480e-a3c7-f84faefeabbc.jpg, location: }, status: SendSucc, rand: 1912880557, seq: 51, note: 点了个赞哈哈哈}`

获取消息：
`getMessages-->[]`

**Comment by JiangJuHong** [comment]
参考腾讯云IM文档
![image](https://user-images.githubusercontent.com/17740963/91970499-505f3100-ed4a-11ea-934a-f0b2d3a6b22e.png)

**Comment by TEENSTITAN** [comment]
A,B 都在群组中（AVChatRoom）中且都在线，A发送消息，B应该能监听到 listener 的 「ListenerTypeEnum.NewMessages」事件啊，可是不知道为何没有调用？

**Comment by JiangJuHong** [comment]
理论上来说是应该能够监听到的，我在项目中实际使用的也是AVChatRoom，但是能够监听到，你有尝试过更换群组吗

**Comment by TEENSTITAN** [comment]
@JiangJuHong 

感谢知道，突然能监听到了，一切OK。
