### ISSUE TITLE
什么时候支持腾讯4.8以上版本的SDK

### ISSUE THREAD

**Issue by JarnTang** [JiangJuHong/FlutterTencentImPlugin#91]
腾讯最新版本到了 4.9.1，有计划支持4.8以上的版本么

**Comment by JiangJuHong** [comment]
有支持机会，暂时不确定支持时间，感谢.

**Comment by JiangJuHong** [comment]
FlutterTencentIM插件已更新至 1.0.x，基于v5 SDK，优化参数、枚举等内容，如需要更新，请参考文档进行更新。注意：由于腾讯云 5.x api改动较大，请不要混用 5.x 和 4.x 接口，对应插件版本: 5.x -> 1.x ，4.x -> 0.x。项目地址：https://github.com/JiangJuHong/FlutterTencentImPlugin
