### ISSUE TITLE
发送的图片消息在接受方收到时会带完整的url，但是语音、视频没有url，这是为什么

### ISSUE THREAD

**Issue by JarnTang** [JiangJuHong/FlutterTencentImPlugin#93]
图片：
![image](https://user-images.githubusercontent.com/791043/92904474-788b1600-f455-11ea-92f7-c0facb0e7db6.png)

语音：
![image](https://user-images.githubusercontent.com/791043/92904900-cef85480-f455-11ea-8f4f-cdaa3199998b.png)

**Comment by JiangJuHong** [comment]
参考如下接口:
![image](https://user-images.githubusercontent.com/17740963/92905219-1088ff80-f456-11ea-99d3-9b7426964317.png)
