### ISSUE TITLE
下载语音时一直报错 PlatformException(4, download failed, download failed)

### ISSUE THREAD

**Issue by JarnTang** [JiangJuHong/FlutterTencentImPlugin#94]
**错误：**
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(4, download failed, download failed)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      TencentImPlugin.downloadSound (package:tencent_im_plugin/tencent_im_plugin.dart:771:27)

**消息内容如下：**
![image](https://user-images.githubusercontent.com/791043/92942966-bd7a7100-f484-11ea-8ece-5cea33c79305.png)

**Comment by JarnTang** [comment]
在下载时 path 参数为 null 时，下载成功了

传入path 和不传的区别在哪里呢，没明白

**Comment by JiangJuHong** [comment]
你这是语音节点，怎么会调用下载图片？

**Comment by JarnTang** [comment]
> 你这是语音节点，怎么会调用下载图片？

标题写错了，是调用的下载语音接口

**Comment by JiangJuHong** [comment]
不传path使用默认值，传递path后使用传递的path，如果没有权限访问则会报错

**Comment by JarnTang** [comment]
> 不传path使用默认值，传递path后使用传递的path，如果没有权限访问则会报错

看了下源码，发现用的是 临时目录 `NSTemporaryDirectory() + "/" + soundElem.uuid;`

我传入的path也是使用的临时目录，不同点在于临时目录下带了子目录，源码里面没有子目录

在临时目录下如果有子目录就需要特殊的权限么？

**Comment by JiangJuHong** [comment]
这个不确定  可以对比下默认生成的目录和你传递的目录

**Comment by JiangJuHong** [comment]
你可以尝试下不传递子目录，如果是因为子目录的原因，可能是因为文件夹没有被创建导致的
