### ISSUE TITLE
update listener not found

### ISSUE THREAD

**Issue by kazeik** [JiangJuHong/FlutterTencentImPlugin#97]
请问一下，消息发送成功，但另一端收不到监听消息，控制台打印：
E/imsdk   (31901): TIM: 2020-09-22 20:54:33.258/E/31901-32209   /IMSDK     -imsdk.ConversationManager.0                                /msg update listener not found

已确定双方互为好友，也确定已经登录，可以拿到登录id.
使用安卓真机向ios模拟器发送消息。

**Comment by JiangJuHong** [comment]
Demo还是你的线上应用?

**Comment by kazeik** [comment]
> Demo还是你的线上应用?

我目前正在开发中的程序，非线上应用。
之前有成功，但后来语音消息弄不出来，把你的demo中的代码拷贝进来，完成了语音消息的整合，
以为事情弄完了。结果，有天拿两端来测试，才发现消息过不来

**Comment by JiangJuHong** [comment]
目前暂未遇见该问题，可以尝试使用Demo是否会遇见该问题

**Comment by kazeik** [comment]
> 目前暂未遇见该问题，可以尝试使用Demo是否会遇见该问题

你的demo .我运行后，报错了。之前还可以的。
想换上我自己用的帐号，签名值这些东西换过来。也是报错。于是放弃了使用你的demo..
所以，现在完全不知道什么个情况了

**Comment by JiangJuHong** [comment]
请尝试运行demo，如果运行不了，请贴出报错信息

**Comment by yaolifei** [comment]
大佬，能搞个qq群吗？我也遇到这个问题

**Comment by JiangJuHong** [comment]
没问题，我明天建一个QQ群，到时候欢迎讨论。

**Comment by songjiabin** [comment]
> 没问题，我明天建一个QQ群，到时候欢迎讨论。

同求，也希望可以请教一些Flutter的问题。

**Comment by JiangJuHong** [comment]
QQ群相关信息已更新到插件主页，欢迎加入QQ群进行讨论

**Comment by kazeik** [comment]
![image](https://user-images.githubusercontent.com/2524383/93970938-a9e2da80-fda1-11ea-8cc5-9c537f669264.png)

session_entity.dart 的第72行，当group = null 时，它的toJson()会引发错误。

**Comment by JiangJuHong** [comment]
我会修改这个问题，并尽快发布下一个版本。

**Comment by JiangJuHong** [comment]
经过验证，此问题不会引起业务逻辑错误，SessionEntity 的 toJson 方法只在特定条件下被触发

**Comment by kazeik** [comment]
> 经过验证，此问题不会引起业务逻辑错误，SessionEntity 的 toJson 方法只在特定条件下被触发

嗯，是的。不会影响消息的发送等业务。
但监听不到消息收发的问题，我估计是腾讯云sdk的问题
