### ISSUE TITLE
TencentImPlugin.getMessages 返回的已读字段（peerReaded) 一直是false的问题

### ISSUE THREAD

**Issue by gwsh** [JiangJuHong/FlutterTencentImPlugin#99]
描述：即使设置了TencentImPlugin.setRead  当我的app杀掉进程或者退出账号再次登录 已读状态就会再次变成false
![image](https://user-images.githubusercontent.com/38830136/94542618-96d97a00-027b-11eb-8f29-072022221118.png)
@JiangJuHong  请问这个是什么原因呢 作者  感谢

**Comment by JiangJuHong** [comment]
你好，我之前也遇到过类似的问题，据我所知是腾讯云需要设置一个东西，具体是什么我忘记了，可以参考腾讯云相关文档.

**Comment by gwsh** [comment]
> 你好，我之前也遇到过类似的问题，据我所知是腾讯云需要设置一个东西，具体是什么我忘记了，可以参考腾讯云相关文档。

你好作者 因该是好友关系检查 不知道你是否有印象 我修改后好像是可以了 但是不太确定
![image](https://user-images.githubusercontent.com/38830136/94544645-136d5800-027e-11eb-87e8-3c5975a4fb12.png)

**Comment by JiangJuHong** [comment]
这个我忘记了，因为很久没接触了，不过可以了的话应该就是这个
